Fix minor bugs and misc issues

diff --git a/usr/bin/mw-all-pages b/usr/bin/mw-all-pages
--- a/usr/bin/mw-all-pages
+++ b/usr/bin/mw-all-pages
@@ -1,6 +1,12 @@
-#!/usr/bin/env bash
+#!/bin/bash
 
-set -euEo pipefail
+## Copyright (C) 2025 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
+## See the file COPYING for copying conditions.
+
+set -o errexit
+set -o nounset
+set -o errtrace
+set -o pipefail
 
 # shellcheck source=../share/mediawiki-shell/common
 source /usr/share/mediawiki-shell/common
@@ -8,15 +14,12 @@ source /usr/share/mediawiki-shell/common
 log info "START"
 
 usage(){
-  printf '%s\n' "Usage: ${0##*/} [OPTIONS] WIKI QUERY OUTPUT
+  printf '%s\n' "Usage: ${0##*/} [OPTIONS] WIKI (allpages|unreviewedpages|querypage) OUTPUT
 Options:
   --article-sanity-test=X        Guarantee that string is present on the fetched pages
   --namespace-default-list=N     Page collection per namespace (default: ${default_namespace_default_list})
   --namespace-extra-list=N       Extra page collection per namespace
 Example:
-  ${0##*/} https://www.kicksecure.com/w
-  ${0##*/} https://www.kicksecure.com/w [allpages|unreviewedpages|querypage]
-  ${0##*/} https://www.kicksecure.com/w allpages /tmp/allpages.txt
   ${0##*/} https://www.kicksecure.com/w allpages /tmp/allpages.txt" >&2
   exit 1
 }
@@ -56,13 +59,15 @@ if [[ -z "${3-}" ]]; then
   usage
 fi
 
-wiki_url="$1"
+WIKI_URL="$1"
 query_type="$2"
 allpages_file="$3"
+
+check_vars_exist query_type allpages_file
 range_arg query_type "${query_type}" allpages unreviewedpages querypage
 
 # shellcheck source=../share/mediawiki-shell/wiki-config
-WIKI_URL="$wiki_url" source /usr/share/mediawiki-shell/wiki-config
+source /usr/share/mediawiki-shell/wiki-config
 
 api_extra_args=""
 case "$query_type" in
@@ -90,22 +95,21 @@ case "$query_type" in
     ## https://www.kicksecure.com/w/api.php?action=query&list=querypage&qppage=Unusedimages
     ;;
   *)
-    log error "query_type must be set to either: allpages, unreviewedpages or querypage"
-    exit 1
+    die 1 "query_type must be set to either: allpages, unreviewedpages or querypage"
     ;;
 esac
 
 safe-rm -f -- "$allpages_file"
 
-log info "allpages_file              : $allpages_file"
+log info "allpages_file         : $allpages_file"
 log info "namespace_default_list: $namespace_default_list"
 log info "namespace_extra_list  : $namespace_extra_list"
-log info "wiki_url  : $wiki_url"
-log info "WIKI_API: $WIKI_API"
+log info "WIKI_URL  : $WIKI_URL"
+log info "WIKI_API  : $WIKI_API"
 log info "query_type: $query_type"
 
 ## Not required for public wiki.
-#mw-login-test "$wiki_url"
+#mw-login-test "$WIKI_URL"
 
 for wiki_namespace_item in $namespace_extra_list $namespace_default_list; do
   log info "wiki_namespace_item: $wiki_namespace_item"
@@ -155,10 +159,8 @@ done
 
 test -f "$allpages_file"
 if [ ! -s "$allpages_file" ]; then
-  log error "allpages_file file is empty!" >&2
-  exit 1
+  die 1 "allpages_file file is empty!" >&2
 fi
-result_test="$(stcat "$allpages_file")"
 
 if [ -z "$article_sanity_test" ]; then
   log info "article_sanity_test not configured, ok."
@@ -168,7 +170,7 @@ fi
 if grep -i -- "$article_sanity_test" "$allpages_file" >/dev/null 2>&1; then
   log info "result_test does contain article_sanity_test '$article_sanity_test', ok. "
 else
-  log error "See script source code. result_test does not contain '$article_sanity_test'! allpages_file: '$allpages_file'"
-  log error "result_test: '$result_test'"
-  exit 1
+  log error "See script source code. result_test does not contain '$article_sanity_test'! allpages_file: '$allpages_file' allpages_file contents:"
+  stcat "$allpages_file" >&2
+  die 1 'article_sanity_test check failed, cannot continue.'
 fi
diff --git a/usr/bin/mw-copy-wiki-file b/usr/bin/mw-copy-wiki-file
--- a/usr/bin/mw-copy-wiki-file
+++ b/usr/bin/mw-copy-wiki-file
@@ -1,14 +1,22 @@
-#!/usr/bin/env bash
+#!/bin/bash
 
-set -euEo pipefail
+## Copyright (C) 2025 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
+## See the file COPYING for copying conditions.
+
+set -o errexit
+set -o nounset
+set -o errtrace
+set -o pipefail
 
 # shellcheck source=../share/mediawiki-shell/common
 source /usr/share/mediawiki-shell/common
 
 log info "START"
 
-usage(){
-  printf '%s\n' "Usage: ${0##*/} WIKI WIKI_TARGET PAGE_FILE [OUTPUT]
+usage() {
+  printf '%s\n' "Usage: ${0##*/} [OPTIONS] WIKI WIKI_TARGET PAGE_FILE [OUTPUT]
+Options:
+  --edit-msg=X     Summary to specify for edit
 Defaults:
   OUTPUT=${default_page_file_local_pretty}
 Example:
@@ -17,26 +25,46 @@ Example:
   exit 1
 }
 
+# shellcheck source=/usr/libexec/helper-scripts/parse_opt.sh
+source /usr/libexec/helper-scripts/parse_opt.sh
+
 default_page_file_local_pretty="$TMPFOLDER/wiki_remote_file_title"
-if [[ -z "${3-}" || "${1-}" =~ (-h|--help) ]]; then
+edit_msg=""
+
+while true; do
+  [[ "${1-}" =~ ^- ]] || break
+  begin_optparse "${1-}" "${2-}" || break
+  true "${opt-}" "${arg-}" "${opt_orig-}"
+  case "${opt}" in
+    edit-msg) get_arg; edit_msg="${arg}";;
+    h|help) usage;;
+    --|"") break;;
+    *) die 2 "Invalid option: '${opt_orig}'"
+  esac
+  shift "${shift_n:-1}"
+done
+
+if [[ -z "${3-}" ]]; then
   usage
 fi
 
-wiki_url="$1"
+WIKI_URL="$1"
 wiki_url_target="$2"
 page_file="$3"
 default_page_file_local="$TMPFOLDER/${page_file}"
 page_file_local="${4-"${default_page_file_local}"}"
 
+check_vars_exist wiki_url_target page_file
+
 wiki_remote_file_title="$(stecho "$page_file" | str_replace "File:" "")"
 
 # shellcheck source=../share/mediawiki-shell/wiki-config
-WIKI_URL="$wiki_url" source /usr/share/mediawiki-shell/wiki-config
+source /usr/share/mediawiki-shell/wiki-config
 
-#mw-login-test "$wiki_url"
+#mw-login-test "$WIKI_URL"
 
-log info "Downloading file '$page_file' '$page_file_local'..."
-mw-file-download "$wiki_url" "$page_file" "$page_file_local"
+log info "Downloading file '$WIKI_URL' '$page_file' '$page_file_local'..."
+mw-file-download "$WIKI_URL" "$page_file" "$page_file_local"
 log info "Download file success."
 
 log info "Checking for pending changes for file..."
@@ -54,13 +82,16 @@ page_pending_status_json=$(
 )
 
 if jq . <<<"$page_pending_status_json" | grep -- pending_since >/dev/null 2>&1; then
-  log warn "'$wiki_url' '$page_file' has PENDING EDITS!"
-  exit 10
+  die 10 "'$WIKI_URL' '$page_file' has PENDING EDITS!"
 fi
 
 log info "No pending edits for file, ok."
-log info "Uploading file... '$wiki_url_target' '$page_file' '$page_file_local'"
+log info "Uploading file... '$wiki_url_target' '$page_file_local' '$wiki_remote_file_title'"
 
-mw-file-upload "${wiki_url_target}" "${page_file_local}" "$wiki_remote_file_title"
+if [ -n "$edit_msg" ]; then
+  mw-file-upload "$wiki_url_target" "$page_file_local" "$wiki_remote_file_title" "$edit_msg"
+else
+  mw-file-upload "$wiki_url_target" "$page_file_local" "$wiki_remote_file_title"
+fi
 
 log info "Upload file success."
diff --git a/usr/bin/mw-copy-wiki-pages b/usr/bin/mw-copy-wiki-pages
--- a/usr/bin/mw-copy-wiki-pages
+++ b/usr/bin/mw-copy-wiki-pages
@@ -1,14 +1,22 @@
-#!/usr/bin/env bash
+#!/bin/bash
 
-set -euEo pipefail
+## Copyright (C) 2025 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
+## See the file COPYING for copying conditions.
+
+set -o errexit
+set -o nounset
+set -o errtrace
+set -o pipefail
 
 # shellcheck source=../share/mediawiki-shell/common
 source /usr/share/mediawiki-shell/common
 
 log info "START"
 
-usage(){
-  printf '%s\n' "Usage: ${0##*/} WIKI WIKI_TARGET PAGE [OUTPUT]
+usage() {
+  printf '%s\n' "Usage: ${0##*/} [OPTIONS] WIKI WIKI_TARGET PAGE [OUTPUT]
+Options:
+  --edit-msg=X     Summary to specify for edit
 Defaults:
   OUTPUT=${default_page_title_local_pretty}
 Example:
@@ -17,27 +25,46 @@ Example:
   exit 1
 }
 
+# shellcheck source=/usr/libexec/helper-scripts/parse_opt.sh
+source /usr/libexec/helper-scripts/parse_opt.sh
+
 default_page_title_local_pretty="$TMPFOLDER/PAGE"
-if [[ -z "${3-}" || "${1-}" =~ (-h|--help) ]]; then
+edit_msg=""
+
+while true; do
+  [[ "${1-}" =~ ^- ]] || break
+  begin_optparse "${1-}" "${2-}" || break
+  true "${opt-}" "${arg-}" "${opt_orig-}"
+  case "${opt}" in
+    edit-msg) get_arg; edit_msg="${arg}";;
+    h|help) usage;;
+    --|"") break;;
+    *) die 2 "Invalid option: '${opt_orig}'"
+  esac
+  shift "${shift_n:-1}"
+done
+
+if [[ -z "${3-}" ]]; then
   usage
 fi
 
-wiki_url="$1"
+WIKI_URL="$1"
 wiki_url_target="$2"
 page_title="$3"
 default_page_title_local="$TMPFOLDER/$page_title"
 page_title_local="${4-"${default_page_title_local}"}"
 
+check_vars_exist wiki_url_target page_title
+
 # shellcheck source=../share/mediawiki-shell/wiki-config
-WIKI_URL="$wiki_url" source /usr/share/mediawiki-shell/wiki-config
+source /usr/share/mediawiki-shell/wiki-config
 
-#mw-login-test "$wiki_url"
+#mw-login-test "$WIKI_URL"
 
-log info "Fetching page '$wiki_url' '$page_title'..."
-
-mw-fetch "$wiki_url" "$page_title" "$page_title_local"
-
+log info "Fetching page '$WIKI_URL' '$page_title' '$page_title_local'..."
+mw-fetch "$WIKI_URL" "$page_title" "$page_title_local"
 log info "Fetch page success."
+
 log info "Checking for pending changes for page..."
 log info "WIKI_API: $WIKI_API"
 
@@ -52,13 +79,17 @@ page_pending_status_json=$(
     "${WIKI_API}?format=json&action=query&prop=info%7Cflagged&titles=$page_title"
 )
 
-if jq . <<<"$page_pending_status_json" | grep -q -- pending_since >/dev/null 2>&1; then
-  log warn "'$wiki_url' '$page_title' page has PENDING EDITS!"
-  exit 10
+if jq . <<<"$page_pending_status_json" | grep -- pending_since >/dev/null 2>&1; then
+  die 10 "'$WIKI_URL' '$page_title' page has PENDING EDITS!"
 fi
 
 log info "No pending edits for page, ok."
+log info "Editing page... '$wiki_url_target' '$page_file_local' '$page_title'"
 
-mw-edit "$wiki_url_target" "$page_title" "$page_title_local"
+if [ -n "$edit_msg" ]; then
+  mw-edit "$wiki_url_target" "$page_title_local" "$page_title" "$edit_msg"
+else
+  mw-edit "$wiki_url_target" "$page_title_local" "$page_title"
+fi
 
 log info "Edit page success."
diff --git a/usr/bin/mw-edit b/usr/bin/mw-edit
--- a/usr/bin/mw-edit
+++ b/usr/bin/mw-edit
@@ -1,16 +1,22 @@
-#!/usr/bin/env bash
+#!/bin/bash
 
-set -euEo pipefail
+## Copyright (C) 2025 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
+## See the file COPYING for copying conditions.
+
+set -o errexit
+set -o nounset
+set -o errtrace
+set -o pipefail
 
 # shellcheck source=../share/mediawiki-shell/common
 source /usr/share/mediawiki-shell/common
 
-usage(){
-  printf '%s\n' "Usage: ${0##*/} WIKI PAGE INPUT [EDIT_MSG]
+usage() {
+  printf '%s\n' "Usage: ${0##*/} WIKI INPUT PAGE [EDIT_MSG]
 Defaults:
   EDIT_MSG=${default_edit_msg}
 Example:
-  ${0##*/} 'https://www.kicksecure.com/w' Ubuntu_software /tmp/a" >&2
+  ${0##*/} 'https://www.kicksecure.com/w' /tmp/a Ubuntu_software" >&2
   exit 1
 }
 
@@ -19,17 +25,22 @@ if [[ -z "${3-}" || "${1-}" =~ (-h|--help) ]]; then
   usage
 fi
 
-wiki_url="$1"
+WIKI_URL="$1"
+new_file="$2"
 page_title="$3"
-new_file="$3"
 edit_msg="${4-"${default_edit_msg}"}"
 
+check_vars_exist new_file page_title
+
 # shellcheck source=../share/mediawiki-shell/wiki-config
-WIKI_URL="$wiki_url" source /usr/share/mediawiki-shell/wiki-config
+source /usr/share/mediawiki-shell/wiki-config
+
+if [ -d "$new_file" ]; then
+  die 1 "new_file '$new_file' is a folder!"
+fi
 
 if [ ! -r "$new_file" ]; then
-  log error "Local file '$new_file' does not exist or is not readable!"
-  exit 2
+  die 2 "Local file '$new_file' does not exist or is not readable!"
 fi
 
 if [ ! -s "$new_file" ]; then
@@ -37,10 +48,10 @@ if [ ! -s "$new_file" ]; then
   exit 0
 fi
 
-log info "Editing page '${wiki_url}' | '${WIKI_API}' | '$page_title'..."
+log info "Editing page '${WIKI_URL}' | '${WIKI_API}' | '$page_title'..."
 #log info "Fetching edit token..."
 
-mw-login-test "$wiki_url"
+mw-login-test "$WIKI_URL"
 
 curl_run \
   "${curl_opts[@]}" \
@@ -53,13 +64,12 @@ curl_run \
   --request "GET" \
   "${WIKI_API}?action=query&meta=tokens&format=json"
 
-csrf_token=$(jq --raw-output '.query.tokens.csrftoken' "${TMPFOLDER}/fetch-edit-token.json")
+csrf_token=$(jq --raw-output '.query.tokens.csrftoken' -- "${TMPFOLDER}/fetch-edit-token.json")
 
 if [ "${#csrf_token}" = 42 ]; then
   log info "Edit token for page OK."
 else
-  log error "Edit token for page not set."
-  exit 1
+  die 1 "Edit token for page not set."
 fi
 
 #log info "Editing '$page_title'..."
@@ -89,13 +99,12 @@ test -r "${TMPFOLDER}/edit-result.json"
 
 edit_result_output="$(stcat "${TMPFOLDER}/edit-result.json")"
 
-edit_result_jq="$(echo "$edit_result_output" | jq -r ".edit.result")"
+edit_result_jq="$(jq -r ".edit.result" <<<"$edit_result_output")"
 
 if [ "$edit_result_jq" = "Success" ]; then
+  log info "Edit page success."
   exit 0
 fi
 
-jq . <<<"$edit_result_output" >&2
-log error "Edit page error."
-
-exit 1
+jq . <<<"$edit_result_output" | stcat >&2
+die 1 "Edit page error."
diff --git a/usr/bin/mw-file-to-web-archive b/usr/bin/mw-file-to-web-archive
--- a/usr/bin/mw-file-to-web-archive
+++ b/usr/bin/mw-file-to-web-archive
@@ -1,6 +1,12 @@
-#!/usr/bin/env bash
+#!/bin/bash
 
-set -euEo pipefail
+## Copyright (C) 2025 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
+## See the file COPYING for copying conditions.
+
+set -o errexit
+set -o nounset
+set -o errtrace
+set -o pipefail
 
 # shellcheck source=../share/mediawiki-shell/common
 source /usr/share/mediawiki-shell/common
@@ -8,23 +14,23 @@ source /usr/share/mediawiki-shell/common
 archive_check() {
   stecho "Checking if already archived by asking web archive... https://web.archive.org/web/$1"
 
-  curl_http_status_code=$($curl "${curl_web_archive_opts[@]}" "https://web.archive.org/web/$1") || true
+  curl_http_status_code="$($curl "${curl_web_archive_opts[@]}" "https://web.archive.org/web/$1")" || true
   curl_output="$(stcat "$TMPFOLDER/webarchive/curl-output-temp")"
 
   if [ "$curl_http_status_code" = "403" ]; then
-    echo "Excluded from web archive."
+    printf '%s\n' "Excluded from web archive."
     stecho "$1" | tee -a -- "$TMPFOLDER/webarchive/already-known-excluded.txt"
     return 0
   fi
 
   if [ "$curl_http_status_code" = "404" ]; then
-    echo "Down according to web archive. curl_http_status_code: '$curl_http_status_code'"
+    printf '%s\n' "Down according to web archive. curl_http_status_code: '$curl_http_status_code'"
     stecho "$1" | tee -a -- "$TMPFOLDER/webarchive/already-known-down.txt"
     return 0
   fi
 
-  location=$(grep -- '^location:' <<<"$curl_output")
-  link=$(awk '{ print $2 }' <<<"$location")
+  location="$(grep -- '^location:' <<<"$curl_output")"
+  link="$(awk '{ print $2 }' <<<"$location")"
   # shellcheck disable=SC2076
   if [[ "$link" =~ "https://web.archive.org/web/" ]]; then
     printf '%s\n' "Already archived according to the web archive. curl_http_status_code: '$curl_http_status_code'"
@@ -32,54 +38,54 @@ archive_check() {
     return 0
   fi
 
-  echo "Not yet archived. curl_http_status_code: $curl_http_status_code | curl_output:"
-  echo "$curl_output"
+  printf '%s\n' "Not yet archived. curl_http_status_code: $curl_http_status_code | curl_output:"
+  printf '%s\n' "$curl_output"
   return 1
 }
 
 archive_save() {
-  echo "Requesting web archive link... https://web.archive.org/save/$1"
+  printf '%s\n' "Requesting web archive link... https://web.archive.org/save/$1"
 
-  curl_http_status_code=$($curl "${curl_web_archive_opts[@]}" "https://web.archive.org/save/$1") || true
+  curl_http_status_code="$($curl "${curl_web_archive_opts[@]}" "https://web.archive.org/save/$1")" || true
   curl_output="$(stcat "$TMPFOLDER/webarchive/curl-output-temp")"
 
   if [ "$curl_http_status_code" = "302" ]; then
-    echo "Archived. Web archive reported that archiving succeeded."
-    location=$(grep -- '^location:' <<<"$curl_output")
-    link=$(awk -- '{ print $2 }' "$location")
+    printf '%s\n' "Archived. Web archive reported that archiving succeeded."
+    location="$(grep -- '^location:' <<<"$curl_output")"
+    link="$(awk -- '{ print $2 }' <<<"$location")"
     printf '%s\n' "$link"
     return 0
   fi
 
   case "$curl_http_status_code" in
     523)
-      echo "Origin link down."
+      printf '%s\n' "Origin link down."
       stecho "$1" | tee -a -- "$TMPFOLDER/webarchive/already-known-down.txt"
       return 0
       ;;
     429)
-      echo "Web archive server denied request, reported too many requests. Waiting for $wait_if_too_many_requests seconds."
+      printf '%s\n' "Web archive server denied request, reported too many requests. Waiting for $wait_if_too_many_requests seconds."
       return 1
       ;;
     520)
-      echo "Web archive unknown error."
+      printf '%s\n' "Web archive unknown error."
       stecho "$1" | tee -a -- "$TMPFOLDER/webarchive/already-known-unknown-error.txt"
       return 0
       ;;
     403)
-      echo "Excluded from web archive."
+      printf '%s\n' "Excluded from web archive."
       stecho "$1" | tee -a -- "$TMPFOLDER/webarchive/already-known-excluded.txt"
       return 0
       ;;
   esac
 
-  echo "Unknown case. curl_http_status_code: $curl_http_status_code | curl_output:"
+  printf '%s\n' "Unknown case. curl_http_status_code: $curl_http_status_code | curl_output:"
   stecho "$curl_output"
   stecho "$1" | tee -a -- "$TMPFOLDER/webarchive/already-unknown-case-error.txt"
   return 0
 }
 
-usage(){
+usage() {
   printf '%s\n' "Usage: ${0##*/} FILE
 Example:
   ${0##*/} ~/sourcesown/web-links.txt" >&2
@@ -117,19 +123,21 @@ while IFS= read -r word; do
   if [ -z "$word" ]; then
     continue
   fi
-  counter=$((counter + 1))
-  echo "$counter / $total | word: '$word'"
-  echo "Checking if already archived in locally cached file..."
+  (( counter++ )) || true
+  printf '%s\n' "$counter / $total | word: '$word'"
+  printf '%s\n' "Checking if already archived in locally cached file..."
 
   do_skip=""
   for cached_file in "$TMPFOLDER"/webarchive/already-*; do
+    if ! [ -f "$cached_file" ]; then
+      continue
+    fi
     if grep --fixed-strings -- "$word" "$cached_file" >/dev/null 2>&1; then
-      echo "Already locally cached file status. cached_file: '$cached_file'"
+      printf '%s\n' "Already locally cached file status. cached_file: '$cached_file'"
       do_skip=true
     fi
   done
   if [ "$do_skip" = "true" ]; then
-    do_skip=true
     continue
   fi
 
@@ -140,5 +148,5 @@ while IFS= read -r word; do
     sleep "$wait_if_too_many_requests"
   done
 
-  echo ""
+  printf '\n'
 done <"$file_name"
diff --git a/usr/bin/mw-file-upload b/usr/bin/mw-file-upload
--- a/usr/bin/mw-file-upload
+++ b/usr/bin/mw-file-upload
@@ -1,11 +1,17 @@
-#!/usr/bin/env bash
+#!/bin/bash
 
-set -euEo pipefail
+## Copyright (C) 2025 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
+## See the file COPYING for copying conditions.
+
+set -o errexit
+set -o nounset
+set -o errtrace
+set -o pipefail
 
 # shellcheck source=../share/mediawiki-shell/common
 source /usr/share/mediawiki-shell/common
 
-usage(){
+usage() {
   printf '%s\n' "Usage: ${0##*/} WIKI INPUT PAGE_FILE [EDIT_MSG]
 Defaults:
   EDIT_MSG=${default_edit_msg}
@@ -19,27 +25,33 @@ default_edit_msg="mediawiki-shell-bot-default-upload-message"
 if [[ -z "${3-}" || "${1-}" =~ (-h|--help) ]]; then
   usage
 fi
-wiki_url="$1"
-origin="$2"
-destination="$3"
+
+WIKI_URL="$1"
+new_file="$2"
+page_file="$3"
 edit_msg="${4-"${default_edit_msg}"}"
 
+check_vars_exist new_file page_file
+
 # shellcheck source=../share/mediawiki-shell/wiki-config
-WIKI_URL="$wiki_url" source /usr/share/mediawiki-shell/wiki-config
+source /usr/share/mediawiki-shell/wiki-config
 
-log info "Uploading file '${wiki_url}' '$origin'..."
-
-if test -d "$origin"; then
-  log error "origin '$origin' is a folder!"
-  exit 1
+if [ -d "$new_file" ]; then
+  die 1 "new_file '$new_file' is a folder!"
 fi
 
-if ! test -r "$origin"; then
-  log error "origin '$origin' is not readable!"
-  exit 1
+if [ ! -r "$new_file" ]; then
+  die 2 "Local file '$new_file' does not exist or is not readable!"
 fi
 
-mw-login-test "$wiki_url"
+if [ ! -s "$new_file" ]; then
+  log info "Local file '$new_file' was empty."
+  exit 0
+fi
+
+log info "Uploading file '${WIKI_URL}' '$new_file'..."
+
+mw-login-test "$WIKI_URL"
 
 curl_run \
   "${curl_opts[@]}" \
@@ -52,13 +64,12 @@ curl_run \
   --request "GET" \
   "${WIKI_API}?action=query&meta=tokens&format=json"
 
-csrf_token=$(jq --raw-output '.query.tokens.csrftoken' "${TMPFOLDER}/fetch-edit-token.json")
+csrf_token=$(jq --raw-output '.query.tokens.csrftoken' -- "${TMPFOLDER}/fetch-edit-token.json")
 
 if [ "${#csrf_token}" = 42 ]; then
   log info "Edit token for file OK."
 else
-  log error "Edit token for file not set."
-  exit 1
+  die 1 "Edit token for file not set."
 fi
 
 curl_run \
@@ -69,8 +80,8 @@ curl_run \
   --header "Connection: keep-alive" \
   --header "Expect:" \
   --form "token=$csrf_token" \
-  --form "filename=$destination" \
-  --form "file=@$origin" \
+  --form "filename=$page_file" \
+  --form "file=@$new_file" \
   --form "comment=$edit_msg" \
   --form "ignorewarnings=yes" \
   --output "${TMPFOLDER}/upload-result.json" \
@@ -82,18 +93,18 @@ log info "Network for file upload ok."
 test -r "${TMPFOLDER}/upload-result.json"
 
 edit_result_output="$(stcat "${TMPFOLDER}/upload-result.json")"
-if [ "$(echo "$edit_result_output" | jq -r ".error.code")" = "fileexists-no-change" ]; then
+if [ "$(jq -r ".error.code" <<<"$edit_result_output")" = "fileexists-no-change" ]; then
   log info "Upload file success."
   exit 0
 fi
 
-edit_result_jq="$(echo "$edit_result_output" | jq -r ".edit.result")"
+edit_result_jq="$(jq -r ".edit.result" <<<"$edit_result_output")"
 if [ "$edit_result_jq" = "Success" ]; then
   log info "Upload (edit) file success."
   exit 0
 fi
 
-upload_result_jq="$(echo "$edit_result_output" | jq -r ".upload.result")"
+upload_result_jq="$(jq -r ".upload.result" <<<"$edit_result_output")"
 if [ "$upload_result_jq" = "Success" ]; then
   log info "Upload (upload) file success."
   exit 0
@@ -101,5 +112,4 @@ fi
 
 log error "Check result on the file: ${TMPFOLDER}/upload-result.json"
 jq . <<<"$edit_result_output" | stcat >&2
-log error "Upload file error."
-exit 1
+die 1 "Upload file error."
diff --git a/usr/bin/mw-multi-wiki b/usr/bin/mw-multi-wiki
--- a/usr/bin/mw-multi-wiki
+++ b/usr/bin/mw-multi-wiki
@@ -1,14 +1,20 @@
-#!/usr/bin/env bash
+#!/bin/bash
 
-set -euEo pipefail
+## Copyright (C) 2025 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
+## See the file COPYING for copying conditions.
+
+set -o errexit
+set -o nounset
+set -o errtrace
+set -o pipefail
 
 # shellcheck source=../share/mediawiki-shell/common
 source /usr/share/mediawiki-shell/common
 
 log info "START"
 
-usage(){
-  printf '%s\n' "Usage: ${0##*/} [WIKI] [WIKI_TARGET] [OUTPUT_DIR]
+usage() {
+  printf '%s\n' "Usage: ${0##*/} [OPTIONS] [WIKI] [WIKI_TARGET] [OUTPUT_DIR]
 Options:
   --continue-from-page=N      Continue from page index
   --multiwiki-category=X      Category of multiwiki (default: ${default_multiwiki_category})
@@ -52,22 +58,23 @@ while true; do
 done
 
 multiwiki_category="${multiwiki_category-"${default_multiwiki_category}"}"
+edit_msg='mediawiki-shell-bot-mirror-multi-wiki-page-from-kicksecure-to-whonix'
 
-wiki_url="${1-"${default_wiki_url}"}"
+WIKI_URL="${1-"${default_wiki_url}"}"
 wiki_url_target="${2-"${default_wiki_url_target}"}"
 output_dir="${3-"${default_output_dir}"}"
 
 # shellcheck source=../share/mediawiki-shell/wiki-config
-WIKI_URL="$wiki_url" source /usr/share/mediawiki-shell/wiki-config
+source /usr/share/mediawiki-shell/wiki-config
 
 allpages_file="${TMPFOLDER}/allpages.txt"
 safe-rm -f -- "$allpages_file"
 
-log info "TMPFOLDER         : $TMPFOLDER"
-log info "wiki_url   : $wiki_url"
-log info "WIKI_API   : $WIKI_API"
-log info "allpages_file     : $allpages_file"
-log info "multiwiki_category: $multiwiki_category"
+log info "TMPFOLDER            : $TMPFOLDER"
+log info "WIKI_URL             : $WIKI_URL"
+log info "WIKI_API             : $WIKI_API"
+log info "allpages_file        : $allpages_file"
+log info "multiwiki_category   : $multiwiki_category"
 log info "multiwiki_extra_pages: $multiwiki_extra_pages"
 
 mkdir --parents -- "$output_dir"
@@ -75,16 +82,16 @@ mkdir --parents -- "$output_dir"
 if ! test -d "$output_dir"; then
   log error "output_dir '$output_dir' does not exist! Run...?:"
   stecho "mkdir --parents -- '$output_dir'"
-  exit 1
+  die 1 "Cannot continue."
 fi
 
 if ! test -w "$output_dir"; then
   log error "output_dir '$output_dir' unwriteable! Run...?:"
   stecho "chown --recursive -- '$USER:$USER' '$output_dir'"
-  exit 1
+  die 1 "Cannot continue."
 fi
 
-mw-login-test "$wiki_url"
+mw-login-test "$WIKI_URL"
 
 all_pages="$(
   $curl \
@@ -95,20 +102,19 @@ all_pages="$(
 ## TODO: cmcontinue
 #https://www.kicksecure.com/w/api.php?action=query&format=json&list=categorymembers&cmtitle=Category:MultiWiki&cmcontinue=page|434f444553454c454354|748
 
-for wiki_multi_extra_wiki_pages_item in $multiwiki_extra_pages; do
-  stecho "$wiki_multi_extra_wiki_pages_item" | tee -a "$allpages_file" >/dev/null
+for multiwiki_extra_pages_item in $multiwiki_extra_pages; do
+  stecho "$multiwiki_extra_pages_item" | tee -a -- "$allpages_file" >/dev/null
 done
 
-stecho "$all_pages" | jq -r ".query.categorymembers[] | .title | @sh" | tee -a "$allpages_file" >/dev/null
+stecho "$all_pages" | jq -r ".query.categorymembers[] | .title | @sh" | tee -a -- "$allpages_file" >/dev/null
 
 test -f "$allpages_file"
 if [ ! -s "$allpages_file" ]; then
-  log error "allpages_file file is empty!" >&2
-  exit 1
+  die 1 "allpages_file file is empty!"
 fi
 counter_total="$(awk 'END {print NR}' "$allpages_file")"
 
-## continue_from_page="Template:VM" mw-multi-wiki
+## mw-multi-wiki --continue-from-page="Template:VM"
 continue_next=no
 if [ -z "$continue_from_page" ]; then
   continue_next=yes
@@ -116,7 +122,7 @@ fi
 
 counter_currently=0
 while IFS=$'\n' read -r item_from_all_pages; do
-  counter_currently=$((counter_currently + 1))
+  (( counter_currently++ )) || true
 
   backup_page_item="$item_from_all_pages"
   ## remove last letter ("'")
@@ -126,9 +132,9 @@ while IFS=$'\n' read -r item_from_all_pages; do
 
   search=" "
   replace="_"
-  backup_page_item=$(stecho "$backup_page_item" | str_replace "$search" "$replace")
+  backup_page_item="$(stecho "$backup_page_item" | str_replace "$search" "$replace")"
 
-  stecho "PAGE | $counter_currently / $counter_total | $item_from_all_pages | $backup_page_item"
+  log info "PAGE | $counter_currently / $counter_total | $item_from_all_pages | $backup_page_item"
 
   if [ "${backup_page_item,,}" = "${continue_from_page,,}" ]; then
     continue_next=yes
@@ -140,11 +146,8 @@ while IFS=$'\n' read -r item_from_all_pages; do
   copy_wiki_pages_exit_code=0
 
   TMPFOLDER="$TMPFOLDER" \
-    mw-copy-wiki-pages "$wiki_url" "$wiki_url_target" "$backup_page_item" ||
-    {
-      copy_wiki_pages_exit_code="$?"
-      true
-    }
+    mw-copy-wiki-pages "--edit-msg=${edit_msg}" "$WIKI_URL" "$wiki_url_target" "$backup_page_item" \
+      || copy_wiki_pages_exit_code="$?"
 
   case "$copy_wiki_pages_exit_code" in
     10)
@@ -159,20 +162,17 @@ while IFS=$'\n' read -r item_from_all_pages; do
   esac
 
   if ! stecho "$backup_page_item" | grep --ignore-case -- "File:" >/dev/null 2>&1; then
-    stecho "FILE | No, not a file, ok."
+    log info "FILE | No, not a file, ok."
     continue
   fi
 
-  stecho "FILE | $counter_currently / $counter_total | $item_from_all_pages | $backup_page_item"
+  log info "FILE | $counter_currently / $counter_total | $item_from_all_pages | $backup_page_item"
 
   copy_wiki_file_exit_code=0
 
   TMPFOLDER="$TMPFOLDER" \
-    mw-copy-wiki-file "$wiki_url" "$wiki_url_target" "$backup_page_item" ||
-    {
-      copy_wiki_file_exit_code="$?"
-      true
-    }
+    mw-copy-wiki-file "--edit-msg=${edit_msg}" "$WIKI_URL" "$wiki_url_target" "$backup_page_item" \
+      || copy_wiki_file_exit_code="$?"
 
   case "$copy_wiki_file_exit_code" in
     10)
@@ -182,7 +182,7 @@ while IFS=$'\n' read -r item_from_all_pages; do
       log info "FILE - backup_page_item '$backup_page_item' mirroring success."
       ;;
     *)
-      die 1 "FILE - backup_page_item '$backup_page_item' mirroring error! copy_wiki_pages_exit_code: '$copy_wiki_file_exit_code'"
+      die 1 "FILE - backup_page_item '$backup_page_item' mirroring error! copy_wiki_file_exit_code: '$copy_wiki_file_exit_code'"
       ;;
   esac
 
diff --git a/usr/bin/mw-wiki-fetch-backup b/usr/bin/mw-wiki-fetch-backup
--- a/usr/bin/mw-wiki-fetch-backup
+++ b/usr/bin/mw-wiki-fetch-backup
@@ -1,6 +1,12 @@
-#!/usr/bin/env bash
+#!/bin/bash
 
-set -euEo pipefail
+## Copyright (C) 2025 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
+## See the file COPYING for copying conditions.
+
+set -o errexit
+set -o nounset
+set -o errtrace
+set -o pipefail
 
 # shellcheck source=../share/mediawiki-shell/common
 source /usr/share/mediawiki-shell/common
@@ -10,17 +16,17 @@ log info "START"
 # shellcheck disable=SC2317
 exit_handler() {
   [[ -v retry_counter ]] || retry_counter=0
-  if [ "$retry_counter" -gt 1 ]; then
+  if (( retry_counter > 1 )); then
     log notice "success after attempt $retry_counter"
   fi
 }
 
 trap exit_handler EXIT
 
-usage(){
-  printf '%s\n' "Usage: ${0##*/} WIKI OUTPUT PAGE
+usage() {
+  printf '%s\n' "Usage: ${0##*/} WIKI PAGE OUTPUT
 Example:
-  ${0##*/} 'https://www.kicksecure.com/w' /tmp/a Some_Article" >&2
+  ${0##*/} 'https://www.kicksecure.com/w' Some_Article /tmp/a" >&2
   exit 1
 }
 
@@ -29,21 +35,21 @@ if [[ -z "${3-}" || "${1-}" =~ (-h|--help) ]]; then
 fi
 
 wiki_url="$1"
-output="$2"
-page="$3"
+page="$2"
+output="$3"
+
+check_vars_exist page output
 
 output_dir="$(dirname "${output}")"
 log info "output_dir: $output_dir"
 
 mkdir -p -- "$output_dir"
 if ! test -d "$output_dir"; then
-  log error "output_dir '$output_dir' does not exist! Run?: mkdir --parents -- '$output_dir'"
-  exit 1
+  die 1 "output_dir '$output_dir' does not exist! Run?: mkdir --parents -- '$output_dir'"
 fi
 
 if ! test -w "$output_dir"; then
-  log error "output_dir '$output_dir' unwriteable! Run?: chown --recursive -- '$USER:$USER' '$output_dir'"
-  exit 1
+  die 1 "output_dir '$output_dir' unwriteable! Run?: chown --recursive -- '$USER:$USER' '$output_dir'"
 fi
 
 for retry_counter in {1..5}; do
@@ -53,4 +59,5 @@ for retry_counter in {1..5}; do
   sleep 5
 done
 
+## Failed even after retry attempts. Therefore exit non-zero.
 exit 1
diff --git a/usr/bin/mw-wiki-link-archiver b/usr/bin/mw-wiki-link-archiver
--- a/usr/bin/mw-wiki-link-archiver
+++ b/usr/bin/mw-wiki-link-archiver
@@ -1,9 +1,12 @@
-#!/usr/bin/env bash
+#!/bin/bash
 
 ## Copyright (C) 2024 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
 ## See the file COPYING for copying conditions.
 
-set -euEo pipefail
+set -o errexit
+set -o nounset
+set -o errtrace
+set -o pipefail
 
 # shellcheck source=../share/mediawiki-shell/common
 source /usr/share/mediawiki-shell/common
@@ -18,13 +21,11 @@ ensure_dir_exists() {
 
   if [ ! -d "${dir_path}" ]; then
     if [ -e "${dir_path}" ]; then
-      log error "${dir_path} exists but is not a directory!"
-      exit 1
+      die 1 "'${dir_path}' exists but is not a directory!"
     fi
-    mkdir -p -- "${dir_path}" || {
-      log error "Could not create a directory at ${dir_path}!"
-      exit 1
-    }
+    if ! mkdir -p -- "${dir_path}"; then
+      die 1 "Could not create a directory at '${dir_path}'!"
+    fi
   fi
 }
 
@@ -36,10 +37,9 @@ ensure_file_exists() {
   file_dir="$(dirname -- "${file_path}")"
 
   ensure_dir_exists "${file_dir}"
-  touch -- "${file_path}" || {
-    log error "Could not touch ${file_path}!"
-    exit 1
-  }
+  if ! touch -- "${file_path}"; then
+    die 1 "Could not touch '${file_path}'!"
+  fi
 }
 
 ensure_wiki_git_up_to_date() {
@@ -60,8 +60,7 @@ ensure_wiki_git_up_to_date() {
       git clone --depth=1 "${wiki_git_repo}"
       popd >/dev/null
     else
-      log error "${wiki_path} has contents, but is not a Git repo!"
-      exit 1
+      die 1 "'${wiki_path}' has contents, but is not a Git repo!"
     fi
   fi
 
@@ -84,8 +83,8 @@ wiki_link_archiver() {
   echo 'Press Enter to begin archiving.'
   read -r captcha_cookie
 
-  # Generates full list of links, this takes a long time so any user input
-  # querying that can be moved before this line should be.
+  ## Generates full list of links, this takes a long time so any user input
+  ## querying that can be moved before this line should be.
   if [ "${skip_link_compilation}" = 'n' ]; then
     mw-wiki-to-weblinks "${input_dir}"
   fi
@@ -119,7 +118,7 @@ wiki_link_archiver() {
     ## skip it
     archive_today_exit_code='0'
     archive.today --find --url "${raw_link}" --captcha-cookie "${captcha_cookie}" || archive_today_exit_code="$?"
-    sleep $(((RANDOM % 11) + 5))
+    sleep $(( (RANDOM % 11) + 5 ))
     if [ "${archive_today_exit_code}" = '0' ]; then
       true
     else
@@ -128,15 +127,15 @@ wiki_link_archiver() {
       ## have a less secure HTTPS configuration.
       if [[ ${raw_link} =~ \.onion$ ]]; then
         # Route onion links through Tor, assumes that tor is running
-        curl --proxy socks5h://127.0.0.1:9050 --location --fail "${raw_link}" >/dev/null 2>&1 || {
+        if ! curl --proxy socks5h://127.0.0.1:9050 --location --fail "${raw_link}" >/dev/null 2>&1; then
           append-once "${error_link_list_file}" "${raw_link}"
           continue
-        }
+        fi
       else
-        curl --location --fail "${raw_link}" >/dev/null 2>&1 || {
+        if ! curl --location --fail "${raw_link}" >/dev/null 2>&1; then
           append-once "${error_link_list_file}" "${raw_link}"
           continue
-        }
+        fi
       fi
 
       ## Try to archive the page, prompting the user for a new CAPTCHA
@@ -144,7 +143,7 @@ wiki_link_archiver() {
       while true; do
         archive_today_exit_code='0'
         archive.today --archive --url "${raw_link}" --captcha-cookie "${captcha_cookie}" || archive_today_exit_code="$?"
-        sleep $(((RANDOM % 11) + 5))
+        sleep $(( (RANDOM % 11) + 5 ))
         if [ "${archive_today_exit_code}" = '0' ]; then
           break
         else
diff --git a/usr/share/mediawiki-shell/common b/usr/share/mediawiki-shell/common
--- a/usr/share/mediawiki-shell/common
+++ b/usr/share/mediawiki-shell/common
@@ -1,5 +1,12 @@
-#!/usr/bin/env bash
-set -euEo pipefail
+#!/bin/bash
+
+## Copyright (C) 2025 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
+## See the file COPYING for copying conditions.
+
+set -o errexit
+set -o nounset
+set -o errtrace
+set -o pipefail
 
 # shellcheck disable=SC1091
 {
@@ -8,8 +15,8 @@ set -euEo pipefail
   source /usr/libexec/helper-scripts/not_as_root.sh
 }
 
-collect_reqs(){
-  local collect
+collect_reqs() {
+  local collect cmd
   collect=""
   for cmd in "${@}"; do
     if ! has "$cmd"; then
@@ -37,7 +44,7 @@ missing_variable() {
 }
 
 error_output() {
-  stecho "error_msg: '${1:-unset}'
+  stecho "error_msg: '${1:-none}'
 WIKI_INDEX: '${WIKI_INDEX-unset}'
 TITLE: '${TITLE-unset}'
 TMPFOLDER: '${TMPFOLDER-unset}'
@@ -59,7 +66,7 @@ trap error_handler ERR
 
 exit_handler() {
   trap - INT HUP ABRT QUIT EXIT
-  local exit_code=$1
+  local exit_code="${1:-}"
   if [ "$exit_code" = "0" ]; then
     log info "END: with OK exit code: '$exit_code'"
   else
@@ -81,7 +88,7 @@ set_backup_page_item() {
 
   backup_page_item="$(stecho "$1")"
   if [ -z "$backup_page_item" ]; then
-    log error "set_backup_filename_item is empty!"
+    die 1 "set_backup_filename_item is empty!"
   fi
 
   ## remove last letter ("'")
@@ -112,7 +119,7 @@ set_backup_filename_item() {
   backup_filename_item="$1"
 
   if [ -z "$backup_filename_item" ]; then
-    log error "backup_filename_item is empty!"
+    die 1 "backup_filename_item is empty!"
   fi
 
   ## Same format as git-mediawiki: replace '/' with '%2F'.
@@ -128,14 +135,14 @@ set_backup_filename_item() {
 }
 
 curl_get_output_parameter() {
-  local loop_counter
+  local loop_counter loop_max
   loop_counter=0
+  loop_max=50
 
   while true; do
-    loop_counter=$((loop_counter + 1))
-    if [ "$loop_counter" -ge 50 ]; then
-      log error "loop_max reached!"
-      exit 1
+    (( loop_counter++ )) || true
+    if (( loop_counter >= loop_max )); then
+      die 1 "loop_max reached!"
     fi
     case $1 in
       --output)
@@ -156,16 +163,15 @@ curl_run() {
   curl_get_output_parameter "$@"
 
   if [ -z "$output_file" ]; then
-    log error "output_file is empty!"
-    exit 1
+    die 1 "output_file is empty!"
   fi
 
   safe-rm -f -- "$output_file"
   touch -- "$output_file"
 
-  local args url encoded_url
-  # shellcheck disable=SC2124,SC1126
-  url="${@: -1}"
+  local temp_args args url encoded_url
+  args=( "$@" )
+  url="${args[$((${#args[@]} - 1))]}"
 
   [[ -v curl_run_no_encode ]] || curl_run_no_encode=""
 
@@ -181,21 +187,18 @@ curl_run() {
   curl_exit_code=0
 
   # Run curl with the modified arguments
-  "$curl" "${args[@]}" || {
-    curl_exit_code=$?
-    true
-  }
+  "$curl" "${args[@]}" || curl_exit_code="$?"
 
-  if [ ! "$curl_exit_code" = "0" ]; then
-    log error "curl failed with exit code '$curl_exit_code': url: '$encoded_url' :output_file: $output_file"
+  if [ "$curl_exit_code" != "0" ]; then
+    log error "curl failed with exit code '$curl_exit_code': url: '$encoded_url' output_file: '$output_file'"
     stcat "$output_file" >&2
-    exit 1
+    die 1 'curl failure, cannot continue.'
   fi
 }
 
 trap 'exit_handler $?' INT HUP ABRT QUIT EXIT
 
-[[ -v TMPFOLDER ]] || TMPFOLDER=~/mediawiki-shell-temp
+[[ -v TMPFOLDER ]] || TMPFOLDER="$HOME/mediawiki-shell-temp"
 [[ -v USERDOMAIN ]] || USERDOMAIN=""
 [[ -v cookie_jar ]] || cookie_jar="$TMPFOLDER/wiki-cookiejar"
 [[ -v curl ]] || set_curl_binary_default
