.

diff --git a/usr/bin/mw-all-pages b/usr/bin/mw-all-pages
--- a/usr/bin/mw-all-pages
+++ b/usr/bin/mw-all-pages
@@ -2,6 +2,7 @@
 
 echo "$0: START"
 
+#set -x
 set -e
 
 source /usr/share/mediawiki-shell/common
@@ -26,6 +27,21 @@ source /usr/share/mediawiki-shell/common
 
 [[ -v wiki_article_must_include_sanity_test ]] || wiki_article_must_include_sanity_test=""
 
+if [ "$QUERY_TYPE" = "allpages" ]; then
+   list=allpages
+   namespace_keyword=apnamespace
+   api_continue_keyword=apcontinue
+   api_limit_keyword_and_content="aplimit=500"
+elif [ "$QUERY_TYPE" = "unreviewedpages" ]; then
+   list=unreviewedpages
+   namespace_keyword=urnamespace
+   api_continue_keyword=urstart
+   api_limit_keyword_and_content="urlimit=500"
+else
+   echo "$0: ERROR: QUERY_TYPE must be set to either QUERY_TYPE=allpages or QUERY_TYPE=unreviewedpages"
+   exit 1
+fi
+
 allpages_file="$1"
 rm -f "$allpages_file"
 
@@ -34,6 +50,7 @@ echo "$0: INFO: wiki_namespace_list_default: $wiki_namespace_list_default"
 echo "$0: INFO: wiki_namespace_list_extra  : $wiki_namespace_list_extra"
 echo "$0: INFO: SOURCE_WIKI_URL  : $SOURCE_WIKI_URL"
 echo "$0: INFO: SOURCE_TARGET_API: $SOURCE_TARGET_API"
+echo "$0: INFO: QUERY_TYPE: $QUERY_TYPE"
 
 ## Not required for public wiki.
 #mw-logout
@@ -45,19 +62,35 @@ for wiki_namespace_item in $wiki_namespace_list_extra $wiki_namespace_list_defau
    api_continue_or_not=""
 
    while true ; do
-      all_pages=$(\
+      echo "$0: INFO: api_full_link:"
+      api_full_link="${SOURCE_TARGET_API}?&format=json&action=query&list=${list}&${namespace_keyword}=${wiki_namespace_item}&${api_limit_keyword_and_content}&${api_continue_keyword}=${api_continue_or_not}"
+      echo "$api_full_link"
+
+      query_result=$(\
          $curl \
             $curl_opts \
-            "${SOURCE_TARGET_API}?action=query&format=json&list=allpages&aplimit=500&apnamespace=${wiki_namespace_item}&apcontinue=${api_continue_or_not}"
+            "$api_full_link"
       )
 
-      echo "$all_pages" | jq -r ".query.allpages[] | .title | @sh" | tee -a "$allpages_file" >/dev/null
-
-      if ! api_continue_or_not=$(echo "$all_pages" | jq -r ".continue | .apcontinue") ; then
-         break
-      fi
-      if [ "$api_continue_or_not" = "null" ]; then
-         break
+      if [ "$QUERY_TYPE" = "allpages" ]; then
+         echo "$query_result" | jq -r ".query.allpages[] | .title | @sh" | tee -a "$allpages_file" >/dev/null
+         ## If curl exits non-zero, consider no longer API continue.
+         ## If curl exits zero, set variable api_continue_or_not.
+         if ! api_continue_or_not=$(echo "$query_result" | jq -r ".continue | .apcontinue") ; then
+            break
+         fi
+         ## If api_continue_or_not is set to "null", we're done.
+         if [ "$api_continue_or_not" = "null" ]; then
+            break
+         fi
+      elif [ "$QUERY_TYPE" = "unreviewedpages" ]; then
+         echo "$query_result" | jq -r '.query.unreviewedpages[] | .title | @sh' | tee -a "$allpages_file" >/dev/null
+         if ! api_continue_or_not=$(echo "$query_result" | jq -r ".continue.urstart") ; then
+            break
+         fi
+         if [ "$api_continue_or_not" = "null" ]; then
+            break
+         fi
       fi
    done
 done
