Minor cleanup

diff --git a/usr/bin/mw-all-pages b/usr/bin/mw-all-pages
--- a/usr/bin/mw-all-pages
+++ b/usr/bin/mw-all-pages
@@ -29,30 +29,35 @@ check_vars_exist SOURCE_WIKI_URL QUERY_TYPE
 [[ -v wiki_article_must_include_sanity_test ]] || wiki_article_must_include_sanity_test=""
 
 api_extra_args=""
-if [ "$QUERY_TYPE" = "allpages" ]; then
-  list=allpages
-  namespace_keyword=apnamespace
-  api_continue_keyword=apcontinue
-  api_limit_keyword_and_content="aplimit=500"
-elif [ "$QUERY_TYPE" = "unreviewedpages" ]; then
-  list=unreviewedpages
-  namespace_keyword=urnamespace
-  api_continue_keyword=urstart
-  api_limit_keyword_and_content="urlimit=500"
-elif [ "$QUERY_TYPE" = "querypage" ]; then
-  list=querypage
-  namespace_keyword=""
-  api_continue_keyword=""
-  api_limit_keyword_and_content="qplimit=500"
-  api_extra_args="&qppage=Unusedimages"
-  ## Upstream does not support name spaces for this API call.
-  wiki_namespace_list_extra=""
-  wiki_namespace_list_default=0
-  ## https://www.kicksecure.com/w/api.php?action=query&list=querypage&qppage=Unusedimages
-else
-  log error "QUERY_TYPE must be set to either QUERY_TYPE=allpages or QUERY_TYPE=unreviewedpages"
-  exit 1
-fi
+case "$QUERY_TYPE" in
+  allpages)
+    list=allpages
+    namespace_keyword=apnamespace
+    api_continue_keyword=apcontinue
+    api_limit_keyword_and_content="aplimit=500"
+    ;;
+  unreviewedpages)
+    list=unreviewedpages
+    namespace_keyword=urnamespace
+    api_continue_keyword=urstart
+    api_limit_keyword_and_content="urlimit=500"
+    ;;
+  querypage)
+    list=querypage
+    namespace_keyword=""
+    api_continue_keyword=""
+    api_limit_keyword_and_content="qplimit=500"
+    api_extra_args="&qppage=Unusedimages"
+    ## Upstream does not support name spaces for this API call.
+    wiki_namespace_list_extra=""
+    wiki_namespace_list_default=0
+    ## https://www.kicksecure.com/w/api.php?action=query&list=querypage&qppage=Unusedimages
+    ;;
+  *)
+    log error "QUERY_TYPE must be set to either: allpages, unreviewedpages or querypage"
+    exit 1
+    ;;
+esac
 
 allpages_file="$1"
 safe-rm -f -- "$allpages_file"
@@ -78,39 +83,40 @@ for wiki_namespace_item in $wiki_namespace_list_extra $wiki_namespace_list_defau
     api_full_link="${SOURCE_TARGET_API}?&format=json&action=query&list=${list}&${namespace_keyword}=${wiki_namespace_item}&${api_limit_keyword_and_content}&${api_continue_keyword}=${api_continue_or_not}${api_extra_args}"
     stecho "$api_full_link"
 
-    query_result=$(
-      $curl \
-        "${curl_opts[@]}" \
-        "$api_full_link"
-    )
+    query_result=$($curl "${curl_opts[@]}" "$api_full_link")
 
-    if [ "$QUERY_TYPE" = "allpages" ]; then
-      stecho "$query_result" | jq -r ".query.allpages[] | .title | @sh" | tee -a "$allpages_file" >/dev/null
-      ## If curl exits non-zero, consider no longer API continue.
-      ## If curl exits zero, set variable api_continue_or_not.
-      if ! api_continue_or_not="$(stecho "$query_result" | jq -r ".continue | .apcontinue")"; then
+    case "$QUERY_TYPE" in
+      allpages)
+        stecho "$query_result" | jq -r ".query.allpages[] | .title | @sh" | tee -a -- "$allpages_file" >/dev/null
+        ## If curl exits non-zero, consider no longer API continue.
+        ## If curl exits zero, set variable api_continue_or_not.
+        if ! api_continue_or_not="$(stecho "$query_result" | jq -r ".continue | .apcontinue")"; then
+          break
+        fi
+        ## If api_continue_or_not is set to "null", we're done.
+        if [ "$api_continue_or_not" = "null" ]; then
+          break
+        fi
+        ;;
+      unreviewedpages)
+        stecho "$query_result" | jq -r '.query.unreviewedpages[] | .title | @sh' | tee -a -- "$allpages_file" >/dev/null
+        if ! api_continue_or_not="$(stecho "$query_result" | jq -r ".continue.urstart")"; then
+          break
+        fi
+        if [ "$api_continue_or_not" = "null" ]; then
+          break
+        fi
+        ;;
+      querypage)
+        stecho "$query_result" | jq -r '.query.querypage.results[] | .title' | tee -a -- "$allpages_file" >/dev/null
+        ## Upstream does not support name spaces for this API call.
         break
-      fi
-      ## If api_continue_or_not is set to "null", we're done.
-      if [ "$api_continue_or_not" = "null" ]; then
+        ;;
+      *)
+        log error "Not implemented!"
         break
-      fi
-    elif [ "$QUERY_TYPE" = "unreviewedpages" ]; then
-      stecho "$query_result" | jq -r '.query.unreviewedpages[] | .title | @sh' | tee -a "$allpages_file" >/dev/null
-      if ! api_continue_or_not="$(stecho "$query_result" | jq -r ".continue.urstart")"; then
-        break
-      fi
-      if [ "$api_continue_or_not" = "null" ]; then
-        break
-      fi
-    elif [ "$QUERY_TYPE" = "querypage" ]; then
-      stecho "$query_result" | jq -r '.query.querypage.results[] | .title' | tee -a "$allpages_file" >/dev/null
-      ## Upstream does not support name spaces for this API call.
-      break
-    else
-      log error "Not implemented!"
-      break
-    fi
+      ;;
+    esac
   done
 done
 
@@ -123,13 +129,14 @@ result_test="$(stcat "$allpages_file")"
 
 if [ -z "$wiki_article_must_include_sanity_test" ]; then
   log info "wiki_article_must_include_sanity_test not configured, ok."
+  exit
+fi
+
+## TODO: stecho too much. ARG_MAX potentially hit. grep based on file instead.
+if stecho "$result_test" | grep -i -- "$wiki_article_must_include_sanity_test" >/dev/null 2>&1; then
+  log info "result_test does contain wiki_article_must_include_sanity_test '$wiki_article_must_include_sanity_test', ok. "
 else
-  ## TODO: stecho too much. ARG_MAX potentially hit. grep based on file instead.
-  if stecho "$result_test" | grep -i -- "$wiki_article_must_include_sanity_test" >/dev/null 2>&1; then
-    log info "result_test does contain wiki_article_must_include_sanity_test '$wiki_article_must_include_sanity_test', ok. "
-  else
-    log error "See script source code. result_test does not contain '$wiki_article_must_include_sanity_test'! allpages_file: '$allpages_file'"
-    log error "result_test: '$result_test'"
-    exit 1
-  fi
+  log error "See script source code. result_test does not contain '$wiki_article_must_include_sanity_test'! allpages_file: '$allpages_file'"
+  log error "result_test: '$result_test'"
+  exit 1
 fi
