.

diff --git a/usr/bin/mw-edit b/usr/bin/mw-edit
--- a/usr/bin/mw-edit
+++ b/usr/bin/mw-edit
@@ -15,18 +15,18 @@ if [ -z "$filename_with_contents" ]; then
 fi
 
 if [ ! -r "$filename_with_contents" ]; then
-  echo "$0: ERROR: File '$filename_with_contents' does not exist!" >&2
+  echo "$0: ERROR: Local file '$filename_with_contents' does not exist!" >&2
   exit 2
 fi
 
 file_content="$(cat "$filename_with_contents")"
 
 if [ "$file_content" = "" ]; then
-  echo "$0: INFO: File '$filename_with_contents' was empty."
+  echo "$0: INFO: Local file '$filename_with_contents' was empty."
   exit 0
 fi
 
-echo "$0: INFO: Editing '${WIKI_URL}' | '${WIKI_API}' | '$TITLE'..."
+echo "$0: INFO: Editing page '${WIKI_URL}' | '${WIKI_API}' | '$TITLE'..."
 #echo "$0: INFO: Fetching edit token..."
 
 mw-logout
@@ -46,9 +46,9 @@ curl_run \
 csrf_token=$(jq --raw-output '.query.tokens.csrftoken' "${TMPFOLDER}/fetch-edit-token.json")
 
 if [ "${#csrf_token}" = 42 ]; then
-   true "$0: INFO: Edit token OK."
+   true "$0: INFO: Edit token for page OK."
 else
-   echo "$0: ERROR: Edit token not set." >&2
+   echo "$0: ERROR: Edit token for page not set." >&2
    exit 1
 fi
 
@@ -73,7 +73,7 @@ curl_run \
    --request "POST" \
    "${WIKI_API}?action=edit&format=json&tags=mediawiki-shell&summary=${edit_message}&bot"
 
-echo "$0: INFO: Network ok."
+echo "$0: INFO: Network for edit page ok."
 
 test -r "${TMPFOLDER}/edit-result.json"
 
@@ -83,11 +83,11 @@ edit_result_jq="$(echo "$edit_result_output" | jq -r ".edit.result")"
 
 if [ "$edit_result_jq" = "Success" ]; then
    echo "$edit_result_output" | jq
-   echo "$0: INFO: Edit success."
+   echo "$0: INFO: Edit page success."
    exit 0
 fi
 
 echo "$edit_result_output" | jq >&2
-echo "$0: ERROR: Edit error." >&2
+echo "$0: ERROR: Edit page error." >&2
 
 exit 1
diff --git a/usr/bin/mw-file-upload b/usr/bin/mw-file-upload
--- a/usr/bin/mw-file-upload
+++ b/usr/bin/mw-file-upload
@@ -43,9 +43,9 @@ curl_run \
 csrf_token=$(jq --raw-output '.query.tokens.csrftoken' "${TMPFOLDER}/fetch-edit-token.json")
 
 if [ "${#csrf_token}" = 42 ]; then
-   true "$0: INFO: Edit token OK."
+   true "$0: INFO: Edit token for file OK."
 else
-   echo "$0: ERROR: Edit token not set." >&2
+   echo "$0: ERROR: Edit token for file not set." >&2
    exit 1
 fi
 
@@ -65,7 +65,7 @@ curl_run \
    --request "POST" \
    "${WIKI_API}?action=upload&format=json&tags=mediawiki-shell&bot"
 
-echo "$0: INFO: Network ok."
+echo "$0: INFO: Network for file upload ok."
 
 test -r "${TMPFOLDER}/upload-result.json"
 
@@ -73,7 +73,7 @@ edit_result_output="$(cat "${TMPFOLDER}/upload-result.json")"
 
 if [ $(echo "$edit_result_output" | jq -r ".error.code") = "fileexists-no-change" ]; then
    #echo "$edit_result_output" | jq
-   echo "$0: INFO: Upload success."
+   echo "$0: INFO: Upload file success."
    exit 0
 fi
 
@@ -81,9 +81,9 @@ edit_result_jq="$(echo "$edit_result_output" | jq -r ".edit.result")"
 
 if [ "$edit_result_jq" = "Success" ]; then
    echo "$edit_result_output" | jq
-   echo "$0: INFO: Upload success."
+   echo "$0: INFO: Upload file success."
    exit 0
 fi
 
 echo "$edit_result_output" | jq >&2
-echo "$0: ERROR: Upload error." >&2
+echo "$0: ERROR: Upload file error." >&2
diff --git a/usr/bin/mw-multi-wiki b/usr/bin/mw-multi-wiki
--- a/usr/bin/mw-multi-wiki
+++ b/usr/bin/mw-multi-wiki
@@ -22,11 +22,12 @@ set -e
 source /usr/share/mediawiki-shell/common
 
 ## Legacy.
-multiwiki_category=MultiWiki
+#multiwiki_category=MultiWiki
 ## TODO
 #multiwiki_category=MultiWikiFile
 #multiwiki_category=MultiWikiContent
 #multiwiki_category=MultiWikiCode
+[[ -v multiwiki_category ]] || multiwiki_category='MultiWiki'
 
 [[ -v multiwiki_category ]] || missing_variable multiwiki_category
 
@@ -44,17 +45,22 @@ multiwiki_category=MultiWiki
 
 [[ -v SOURCE_WIKI_API ]] || SOURCE_WIKI_API="${SOURCE_WIKI_URL}/api.php"
 
-[[ -v wiki_multi_extra_wiki_pages_list ]] || wiki_multi_extra_wiki_pages_list="'MediaWiki:Build.json'"
+if [ ! "$multiwiki_category" = "MultiWikiFile" ]; then
+   [[ -v wiki_multi_extra_wiki_pages_list ]] || wiki_multi_extra_wiki_pages_list="'MediaWiki:Build.json'"
+fi
+[[ -v wiki_multi_extra_wiki_pages_list ]] || wiki_multi_extra_wiki_pages_list=""
 
 allpages_file="${TMPFOLDER}/allpages.txt"
 rm -f "$allpages_file"
 
 temp_article="${TMPFOLDER}/temp_article.txt"
 
-echo "$0: INFO: TMPFOLDER      : $TMPFOLDER"
-echo "$0: INFO: SOURCE_WIKI_URL: $SOURCE_WIKI_URL"
-echo "$0: INFO: SOURCE_WIKI_API: $SOURCE_WIKI_API"
-echo "$0: INFO: allpages_file  : $allpages_file"
+echo "$0: INFO: TMPFOLDER         : $TMPFOLDER"
+echo "$0: INFO: SOURCE_WIKI_URL   : $SOURCE_WIKI_URL"
+echo "$0: INFO: SOURCE_WIKI_API   : $SOURCE_WIKI_API"
+echo "$0: INFO: allpages_file     : $allpages_file"
+echo "$0: INFO: multiwiki_category: $multiwiki_category"
+echo "$0: INFO: wiki_multi_extra_wiki_pages_list: $wiki_multi_extra_wiki_pages_list"
 
 mkdir --parents "$wiki_backup_folder"
 
@@ -120,17 +126,42 @@ while IFS=$'\n' read -r item_from_all_pages ; do
    DESTINATION_WIKI_URL="$DESTINATION_WIKI_URL" \
    TMPFOLDER="$TMPFOLDER" \
    copy_wiki_pages_item="$backup_page_item" \
-   edit_message="mediawiki-shell-bot-mirror-multi-wiki-from-kicksecure-to-whonix" \
+   edit_message="mediawiki-shell-bot-mirror-multi-wiki-page-from-kicksecure-to-whonix" \
       mw-copy-wiki-pages \
          || { copy_wiki_pages_exit_code="$?" ; true; }
 
    if [ "$copy_wiki_pages_exit_code" = "10" ]; then
-      echo "$0: WARNING: Skipped backup_page_item '$backup_page_item' because of pending edits."
+      echo "$0: WARNING: PAGE - Skipped backup_page_item '$backup_page_item' because of pending edits."
    elif [ "$copy_wiki_pages_exit_code" = "0" ]; then
-      echo "$0: INFO: backup_page_item '$backup_page_item' mirroring success."
+      echo "$0: INFO: PAGE - backup_page_item '$backup_page_item' mirroring success."
    else
-      echo "$0: ERROR: backup_page_item '$backup_page_item' mirroring error! copy_wiki_pages_exit_code: '$copy_wiki_pages_exit_code'"
+      echo "$0: ERROR: PAGE - backup_page_item '$backup_page_item' mirroring error! copy_wiki_pages_exit_code: '$copy_wiki_pages_exit_code'"
       exit 1
    fi
+
+   if [ ! "$multiwiki_category" = "MultiWikiFile" ]; then
+      continue
+   fi
+
+   copy_wiki_file_exit_code=0
+
+   SOURCE_WIKI_URL="$SOURCE_WIKI_URL" \
+   DESTINATION_WIKI_URL="$DESTINATION_WIKI_URL" \
+   TMPFOLDER="$TMPFOLDER" \
+   wiki_remote_file_name="$backup_page_item" \
+   edit_message="mediawiki-shell-bot-mirror-multi-wiki-file-from-kicksecure-to-whonix" \
+      mw-copy-wiki-file \
+         || { copy_wiki_file_exit_code="$?" ; true; }
+
+   if [ "$copy_wiki_file_exit_code" = "10" ]; then
+      echo "$0: WARNING: FILE - Skipped backup_page_item '$backup_page_item' because of pending edits."
+   elif [ "$copy_wiki_file_exit_code" = "0" ]; then
+      echo "$0: INFO: FILE - backup_page_item '$backup_page_item' mirroring success."
+   else
+      echo "$0: ERROR: FILE - backup_page_item '$backup_page_item' mirroring error! copy_wiki_pages_exit_code: '$copy_wiki_file_exit_code'"
+      exit 1
+   fi
+
+   continue
 
 done < "$allpages_file"
