.

diff --git a/usr/bin/mw-edit b/usr/bin/mw-edit
--- a/usr/bin/mw-edit
+++ b/usr/bin/mw-edit
@@ -10,19 +10,19 @@ filename_with_contents="$2"
 [[ -v edit_message ]] || edit_message="mediawiki-shell-bot-default-edit-message"
 
 if [ -z "$filename_with_contents" ]; then
-  echo "$0: ERROR: Syntax: $0 <page_to_edit> <new_content_file>"
+  echo "$0: ERROR: Syntax: $0 <page_to_edit> <new_content_file>" >&2
   exit 1
 fi
 
 if [ ! -r "$filename_with_contents" ]; then
-  echo "$0: ERROR: File '$filename_with_contents' does not exist!"
+  echo "$0: ERROR: File '$filename_with_contents' does not exist!" >&2
   exit 2
 fi
 
 file_content="$(cat "$filename_with_contents")"
 
 if [ "$file_content" = "" ]; then
-  echo "$0: ERROR: File '$filename_with_contents' must not be empty!"
+  echo "$0: ERROR: File '$filename_with_contents' must not be empty!" >&2
   exit 3
 fi
 
@@ -48,7 +48,7 @@ csrf_token=$(jq --raw-output '.query.tokens.csrftoken' "${TMPFOLDER}/fetch-edit-
 if [ "${#csrf_token}" = 42 ]; then
    true "$0: INFO: Edit token OK."
 else
-   echo "$0: ERROR: Edit token not set."
+   echo "$0: ERROR: Edit token not set." >&2
    exit 1
 fi
 
diff --git a/usr/bin/mw-login b/usr/bin/mw-login
--- a/usr/bin/mw-login
+++ b/usr/bin/mw-login
@@ -5,7 +5,7 @@ source /usr/share/mediawiki-shell/common
 source /usr/share/mediawiki-shell/wiki-config
 
 if [ -z "$WIKI_API_USER_PASS" ]; then
-   echo "$0: ERROR: Password not supplied!"
+   echo "$0: ERROR: Password not supplied!" >&2
    exit 1
 fi
 
@@ -57,6 +57,6 @@ if [ "$RESULT" = "Success" ]; then
    exit 0
 fi
 
-cat "${TMPFOLDER}/login-result.json" | jq
-echo "$0: ERROR: Login failed!"
+cat "${TMPFOLDER}/login-result.json" | jq >&2
+echo "$0: ERROR: Login failed!" >&2
 exit 1
diff --git a/usr/bin/mw-logout b/usr/bin/mw-logout
--- a/usr/bin/mw-logout
+++ b/usr/bin/mw-logout
@@ -37,6 +37,6 @@ if [ $(cat "${TMPFOLDER}/logout.json") = "{}" ] ; then
    exit 0
 fi
 
-cat "${TMPFOLDER}/logout.json" | jq
-echo "$0: ERROR: Logout failed!"
+cat "${TMPFOLDER}/logout.json" | jq >&2
+echo "$0: ERROR: Logout failed!" >&2
 exit 1
