.

diff --git a/usr/bin/mw-edit b/usr/bin/mw-edit
--- a/usr/bin/mw-edit
+++ b/usr/bin/mw-edit
@@ -32,7 +32,7 @@ echo "$0: INFO: Editing '${WIKI_URL}' | '${WIKI_API}' | '$TITLE'..."
 mw-logout
 mw-login
 
-$curl \
+if ! $curl \
    $curl_opts \
    --cookie "$cookie_jar" \
    --cookie-jar "$cookie_jar" \
@@ -41,7 +41,10 @@ $curl \
    --compressed \
    --output "${TMPFOLDER}/fetch-edit-token.json" \
    --request "GET" \
-   "${WIKI_API}?action=query&meta=tokens&format=json"
+   "${WIKI_API}?action=query&meta=tokens&format=json" ; then
+      echo "$0: ERROR: curl fetch edit token failed with exit code $?. ${TMPFOLDER}/fetch-edit-token.json:" >&2
+      cat "${TMPFOLDER}/fetch-edit-token.json" >&2
+fi
 
 csrf_token=$(jq --raw-output '.query.tokens.csrftoken' "${TMPFOLDER}/fetch-edit-token.json")
 
@@ -59,7 +62,7 @@ fi
 ## Need to create wiki tag mediawiki-shell here:
 ## https://www.whonix.org/wiki/Special:Tags
 
-$curl \
+if ! $curl \
    $curl_opts \
    --cookie "$cookie_jar" \
    --cookie-jar "$cookie_jar" \
@@ -71,7 +74,10 @@ $curl \
    --data-urlencode "token=$csrf_token" \
    --output "${TMPFOLDER}/edit-result.json" \
    --request "POST" \
-   "${WIKI_API}?action=edit&format=json&tags=mediawiki-shell&summary=${edit_message}&bot"
+   "${WIKI_API}?action=edit&format=json&tags=mediawiki-shell&summary=${edit_message}&bot" ; then
+      echo "$0: ERROR: curl edit failed with exit code $?. ${TMPFOLDER}/edit-result.json" >&2
+      cat "${TMPFOLDER}/edit-result.json" >&2
+fi
 
 echo "$0: INFO: Network ok."
 
diff --git a/usr/bin/mw-login b/usr/bin/mw-login
--- a/usr/bin/mw-login
+++ b/usr/bin/mw-login
@@ -14,7 +14,7 @@ echo "$0: INFO: Logging into '$WIKI_API' as '$WIKI_API_USER_NAME'... Requesting 
 rm -f "${TMPFOLDER}/login-token.json"
 rm -f "${TMPFOLDER}/login-result.json"
 
-$curl \
+if ! $curl \
    $curl_opts \
    --cookie "$cookie_jar" \
    --cookie-jar "$cookie_jar" \
@@ -22,7 +22,10 @@ $curl \
    --header "Accept-Language: en-GB" \
    --output "${TMPFOLDER}/login-token.json" \
    --request "POST" \
-   "${WIKI_API}?action=query&meta=tokens&type=login&format=json"
+   "${WIKI_API}?action=query&meta=tokens&type=login&format=json" ; then
+      echo "$0: ERROR: curl login failed with exit code $?. ${TMPFOLDER}/login-token.json" >&2
+      cat "${TMPFOLDER}/login-token.json" >&2
+fi
 
 echo "$0: INFO: Login Token received."
 
@@ -31,7 +34,7 @@ login_token=$(cat "${TMPFOLDER}/login-token.json" | jq --raw-output '.query.toke
 ## Sensitive?
 #echo "$0: INFO: login_token: $login_token"
 
-$curl \
+if ! $curl \
    $curl_opts \
    --cookie "$cookie_jar" \
    --cookie-jar "$cookie_jar" \
@@ -42,7 +45,10 @@ $curl \
    --data-urlencode "lgtoken=${login_token}" \
    --output "${TMPFOLDER}/login-result.json" \
    --request "POST" \
-   "${WIKI_API}?action=login&format=json"
+   "${WIKI_API}?action=login&format=json" ; then
+      echo "$0: ERROR: curl result failed with exit code $?. ${TMPFOLDER}/login-result.json" >&2
+      cat "${TMPFOLDER}/login-result.json" >&2
+fi
 
 ## XXX:
 ## If already logged in:
diff --git a/usr/bin/mw-logout b/usr/bin/mw-logout
--- a/usr/bin/mw-logout
+++ b/usr/bin/mw-logout
@@ -8,7 +8,7 @@ echo "$0: INFO: Logging out of $WIKI_API... Requesting CSRF token..."
 
 rm -f "${TMPFOLDER}/logout-token.json"
 
-$curl \
+if ! $curl \
    $curl_opts \
    --cookie "$cookie_jar" \
    --cookie-jar "$cookie_jar" \
@@ -16,13 +16,16 @@ $curl \
    --header "Accept-Language: en-GB" \
    --output "${TMPFOLDER}/logout-token.json" \
    --request "POST" \
-   "${WIKI_API}?action=query&meta=tokens&type=csrf&format=json"
+   "${WIKI_API}?action=query&meta=tokens&type=csrf&format=json" ; then
+      echo "$0: ERROR: curl logout-token failed with exit code $?. ${TMPFOLDER}/login-result.json" >&2
+      cat "${TMPFOLDER}/login-result.json" >&2
+fi
 
 echo "$0: INFO: Token received."
 
 csrf_token=$(cat "${TMPFOLDER}/logout-token.json" | jq --raw-output '.query.tokens.csrftoken')
 
-$curl \
+if ! $curl \
    $curl_opts \
    --cookie "$cookie_jar" \
    --cookie-jar "$cookie_jar" \
@@ -30,7 +33,10 @@ $curl \
    --data-urlencode "token=${csrf_token}" \
    --output "${TMPFOLDER}/logout.json" \
    --request "POST" \
-   "${WIKI_API}?action=logout&format=json"
+   "${WIKI_API}?action=logout&format=json" ; then
+      echo "$0: ERROR: curl logout failed with exit code $?. ${TMPFOLDER}/logout.json" >&2
+      cat "${TMPFOLDER}/logout.json" >&2
+fi
 
 if [ $(cat "${TMPFOLDER}/logout.json") = "{}" ] ; then
    echo "$0: INFO: OK, logged out."
