Shell formatting
shfmt -w -s -i 2 -ci usr/

diff --git a/usr/bin/mw-file-to-web-archive b/usr/bin/mw-file-to-web-archive
--- a/usr/bin/mw-file-to-web-archive
+++ b/usr/bin/mw-file-to-web-archive
@@ -28,78 +28,78 @@ echo "$TMPFOLDER/webarchive/already-archived.txt"
 echo "$TMPFOLDER/webarchive/already-known-down.txt"
 
 archive_check() {
-   echo "Checking if already archived by asking web archive... https://web.archive.org/web/$1"
+  echo "Checking if already archived by asking web archive... https://web.archive.org/web/$1"
 
-   curl_http_status_code=$($curl $curl_web_archive_opts "https://web.archive.org/web/$1") || true
-   curl_output="$(cat "$TMPFOLDER/webarchive/curl-output-temp")"
+  curl_http_status_code=$($curl $curl_web_archive_opts "https://web.archive.org/web/$1") || true
+  curl_output="$(cat "$TMPFOLDER/webarchive/curl-output-temp")"
 
-   if [ "$curl_http_status_code" = "403" ]; then
-      echo "Excluded from web archive."
-      echo "$1" | tee -a "$TMPFOLDER/webarchive/already-known-excluded.txt"
-      return 0
-   fi
+  if [ "$curl_http_status_code" = "403" ]; then
+    echo "Excluded from web archive."
+    echo "$1" | tee -a "$TMPFOLDER/webarchive/already-known-excluded.txt"
+    return 0
+  fi
 
-   if [ "$curl_http_status_code" = "404" ]; then
-      echo "Down according to web archive. curl_http_status_code: '$curl_http_status_code'"
-      echo "$1" | tee -a "$TMPFOLDER/webarchive/already-known-down.txt"
-      return 0
-   fi
+  if [ "$curl_http_status_code" = "404" ]; then
+    echo "Down according to web archive. curl_http_status_code: '$curl_http_status_code'"
+    echo "$1" | tee -a "$TMPFOLDER/webarchive/already-known-down.txt"
+    return 0
+  fi
 
-   location=$(printf '%s\n' "$curl_output" | grep -- '^location:')
-   link=$(printf '%s\n' "$location" | awk '{ print $2 }')
-   if printf '%s\n' "$link" | grep --fixed-strings -- "https://web.archive.org/web/" >/dev/null 2>/dev/null; then
-      printf '%s\n' "Already archived according to the web archive. curl_http_status_code: '$curl_http_status_code'"
-      printf '%s\n' "$1" | tee -a "$TMPFOLDER/webarchive/already-archived.txt"
-      printf '%s\n' "$link" | tee -a "$TMPFOLDER/webarchive/already-archived.txt"
-      return 0
-   fi
+  location=$(printf '%s\n' "$curl_output" | grep -- '^location:')
+  link=$(printf '%s\n' "$location" | awk '{ print $2 }')
+  if printf '%s\n' "$link" | grep --fixed-strings -- "https://web.archive.org/web/" >/dev/null 2>/dev/null; then
+    printf '%s\n' "Already archived according to the web archive. curl_http_status_code: '$curl_http_status_code'"
+    printf '%s\n' "$1" | tee -a "$TMPFOLDER/webarchive/already-archived.txt"
+    printf '%s\n' "$link" | tee -a "$TMPFOLDER/webarchive/already-archived.txt"
+    return 0
+  fi
 
-   echo "Not yet archived. curl_http_status_code: $curl_http_status_code | curl_output:"
-   echo "$curl_output"
-   return 1
+  echo "Not yet archived. curl_http_status_code: $curl_http_status_code | curl_output:"
+  echo "$curl_output"
+  return 1
 }
 
 archive_save() {
-   echo "Requesting web archive link... https://web.archive.org/save/$1"
+  echo "Requesting web archive link... https://web.archive.org/save/$1"
 
-   curl_http_status_code=$($curl $curl_web_archive_opts "https://web.archive.org/save/$1") || true
-   curl_output="$(cat "$TMPFOLDER/webarchive/curl-output-temp")"
+  curl_http_status_code=$($curl $curl_web_archive_opts "https://web.archive.org/save/$1") || true
+  curl_output="$(cat "$TMPFOLDER/webarchive/curl-output-temp")"
 
-   if [ "$curl_http_status_code" = "302" ]; then
-      printf '%s\n' "Archived. Web archive reported that archiving succeeded."
-      location=$(printf '%s\n' "$curl_output" | grep -- '^location:')
-      link=$(printf '%s\n' "$location" | awk '{ print $2 }')
-      printf '%s\n' "$link"
-      return 0
-   fi
+  if [ "$curl_http_status_code" = "302" ]; then
+    printf '%s\n' "Archived. Web archive reported that archiving succeeded."
+    location=$(printf '%s\n' "$curl_output" | grep -- '^location:')
+    link=$(printf '%s\n' "$location" | awk '{ print $2 }')
+    printf '%s\n' "$link"
+    return 0
+  fi
 
-   if [ "$curl_http_status_code" = "523" ]; then
-      echo "Origin link down."
-      echo "$1" | tee -a "$TMPFOLDER/webarchive/already-known-down.txt"
-      return 0
-   fi
+  if [ "$curl_http_status_code" = "523" ]; then
+    echo "Origin link down."
+    echo "$1" | tee -a "$TMPFOLDER/webarchive/already-known-down.txt"
+    return 0
+  fi
 
-   if [ "$curl_http_status_code" = "429" ]; then
-      echo "Web archive server denied request, reported too many requests. Waiting for $wait_if_too_many_requests seconds."
-      return 1
-   fi
+  if [ "$curl_http_status_code" = "429" ]; then
+    echo "Web archive server denied request, reported too many requests. Waiting for $wait_if_too_many_requests seconds."
+    return 1
+  fi
 
-   if [ "$curl_http_status_code" = "520" ]; then
-      echo "Web archive unknown error."
-      echo "$1" | tee -a "$TMPFOLDER/webarchive/already-known-unknown-error.txt"
-      return 0
-   fi
+  if [ "$curl_http_status_code" = "520" ]; then
+    echo "Web archive unknown error."
+    echo "$1" | tee -a "$TMPFOLDER/webarchive/already-known-unknown-error.txt"
+    return 0
+  fi
 
-   if [ "$curl_http_status_code" = "403" ]; then
-      echo "Excluded from web archive."
-      echo "$1" | tee -a "$TMPFOLDER/webarchive/already-known-excluded.txt"
-      return 0
-   fi
+  if [ "$curl_http_status_code" = "403" ]; then
+    echo "Excluded from web archive."
+    echo "$1" | tee -a "$TMPFOLDER/webarchive/already-known-excluded.txt"
+    return 0
+  fi
 
-   echo "Unknown case. curl_http_status_code: $curl_http_status_code | curl_output:"
-   echo "$curl_output"
-   echo "$1" | tee -a "$TMPFOLDER/webarchive/already-unknown-case-error.txt"
-   return 0
+  echo "Unknown case. curl_http_status_code: $curl_http_status_code | curl_output:"
+  echo "$curl_output"
+  echo "$1" | tee -a "$TMPFOLDER/webarchive/already-unknown-case-error.txt"
+  return 0
 }
 
 #set -x
@@ -115,38 +115,38 @@ total="$(awk 'END {print NR}' "$file_name")"
 
 counter=0
 
-cat < "$file_name" | while IFS= read -r word; do
-   if [ "$word" = "" ]; then
-      continue
-   fi
+cat <"$file_name" | while IFS= read -r word; do
+  if [ "$word" = "" ]; then
+    continue
+  fi
 
-   counter=$(( counter + 1 ))
-   echo "$counter / $total | word: '$word'"
+  counter=$((counter + 1))
+  echo "$counter / $total | word: '$word'"
 
-   echo "Checking if already archived in locally cached file..."
+  echo "Checking if already archived in locally cached file..."
 
-   do_skip=""
-   for cached_file in $TMPFOLDER/webarchive/already-* ; do
-      if grep --fixed-strings -- "$word" "$cached_file" >/dev/null 2>/dev/null ; then
-         echo "Already locally cached file status. cached_file: '$cached_file'"
-         do_skip=true
-      fi
-   done
-   if [ "$do_skip" = "true" ]; then
+  do_skip=""
+  for cached_file in $TMPFOLDER/webarchive/already-*; do
+    if grep --fixed-strings -- "$word" "$cached_file" >/dev/null 2>/dev/null; then
+      echo "Already locally cached file status. cached_file: '$cached_file'"
       do_skip=true
-      continue
-   fi
+    fi
+  done
+  if [ "$do_skip" = "true" ]; then
+    do_skip=true
+    continue
+  fi
 
-   for retry_counter in $(seq 1 60) ; do
-      if archive_check "$word" ; then
-         break
-      fi
+  for retry_counter in $(seq 1 60); do
+    if archive_check "$word"; then
+      break
+    fi
 
-      if archive_save "$word" ; then
-         break
-      fi
-      sleep "$wait_if_too_many_requests"
-   done
+    if archive_save "$word"; then
+      break
+    fi
+    sleep "$wait_if_too_many_requests"
+  done
 
-   echo ""
+  echo ""
 done
diff --git a/usr/bin/mw-flagged-revisions-approve-all b/usr/bin/mw-flagged-revisions-approve-all
--- a/usr/bin/mw-flagged-revisions-approve-all
+++ b/usr/bin/mw-flagged-revisions-approve-all
@@ -30,19 +30,22 @@ log info "SOURCE_WIKI_URL  : $SOURCE_WIKI_URL"
 log info "SOURCE_TARGET_API: $SOURCE_TARGET_API"
 
 login_function() {
-   log info "Logging in..."
-   WIKI_URL="$SOURCE_WIKI_URL" mw-logout
-   WIKI_URL="$SOURCE_WIKI_URL" mw-login
-   log info "Login ok."
+  log info "Logging in..."
+  WIKI_URL="$SOURCE_WIKI_URL" mw-logout
+  WIKI_URL="$SOURCE_WIKI_URL" mw-login
+  log info "Login ok."
 }
 
 approve_page() {
-   approve_page_exit_code=0
+  approve_page_exit_code=0
 
-   SOURCE_WIKI_URL="$SOURCE_WIKI_URL" \
-   DESTINATION_WIKI_PAGE="$backup_page_item" \
-      mw-flagged-revisions-approve-page \
-         "$backup_page_item" || { approve_page_exit_code="$?" ; true; };
+  SOURCE_WIKI_URL="$SOURCE_WIKI_URL" \
+    DESTINATION_WIKI_PAGE="$backup_page_item" \
+    mw-flagged-revisions-approve-page \
+    "$backup_page_item" || {
+    approve_page_exit_code="$?"
+    true
+  }
 }
 
 login_function
@@ -51,8 +54,8 @@ allpages_file="${TMPFOLDER}/allpages.txt"
 rm -f "$allpages_file"
 
 QUERY_TYPE=unreviewedpages \
-SOURCE_WIKI_URL="$SOURCE_WIKI_URL" \
-   mw-all-pages "$allpages_file"
+  SOURCE_WIKI_URL="$SOURCE_WIKI_URL" \
+  mw-all-pages "$allpages_file"
 
 test -r "$allpages_file"
 
@@ -60,37 +63,37 @@ counter_total="$(awk 'END {print NR}' "$allpages_file")"
 
 counter_currently=0
 error_counter=0
-while IFS=$'\n' read -r item_from_all_pages ; do
-   counter_currently=$(( $counter_currently + 1 ))
-   backup_page_item=$(set_backup_page_item "$item_from_all_pages")
-   log info "$counter_currently / $counter_total"
-   echo "\
+while IFS=$'\n' read -r item_from_all_pages; do
+  counter_currently=$((counter_currently + 1))
+  backup_page_item=$(set_backup_page_item "$item_from_all_pages")
+  log info "$counter_currently / $counter_total"
+  echo "\
 SOURCE_WIKI_URL='$SOURCE_WIKI_URL' \
 DESTINATION_WIKI_PAGE='$backup_page_item' \
 mw-flagged-revisions-approve-page \
 '$backup_page_item'"
 
-   approve_page
-   if [ "$approve_page_exit_code" = "0" ]; then
-      log info "Success at first attempt, ok."
-      continue
-   elif [ "$approve_page_exit_code" = "254" ]; then
-      log info "Got exit code 254. Login probably expired."
-      login_function
-      log info "Try again..."
-      approve_page
-   fi
+  approve_page
+  if [ "$approve_page_exit_code" = "0" ]; then
+    log info "Success at first attempt, ok."
+    continue
+  elif [ "$approve_page_exit_code" = "254" ]; then
+    log info "Got exit code 254. Login probably expired."
+    login_function
+    log info "Try again..."
+    approve_page
+  fi
 
-   if [ "$approve_page_exit_code" = "0" ]; then
-      log info "Success after second attempt, ok."
-   else
-      error_counter=$(( $error_counter + 1 ))
-      log error "Failed!"
-   fi
-done < "$allpages_file"
+  if [ "$approve_page_exit_code" = "0" ]; then
+    log info "Success after second attempt, ok."
+  else
+    error_counter=$((error_counter + 1))
+    log error "Failed!"
+  fi
+done <"$allpages_file"
 
 if [ "$error_counter" = "0" ]; then
-   log info "Success."
+  log info "Success."
 else
-   log warning "$error_counter error(s) detected."
+  log warning "$error_counter error(s) detected."
 fi
diff --git a/usr/bin/mw-multi-wiki b/usr/bin/mw-multi-wiki
--- a/usr/bin/mw-multi-wiki
+++ b/usr/bin/mw-multi-wiki
@@ -1,19 +1,19 @@
 #!/bin/bash
 
 missing_variable() {
-   log error "missing variable '$1'!"
-   exit 1
+  log error "missing variable '$1'!"
+  exit 1
 }
 
 # TODO: ben: Unused function and variable. Confirm deletion.
 error_out_maybe() {
-   if [ "$wiki_error_on_fetch" = "true" ]; then
-      ## error out
-      return 1
-   else
-      ## ignore error
-      return 0
-   fi
+  if [ "$wiki_error_on_fetch" = "true" ]; then
+    ## error out
+    return 1
+  else
+    ## ignore error
+    return 0
+  fi
 }
 
 log info "START"
@@ -29,7 +29,7 @@ source /usr/share/mediawiki-shell/common
 ## example:
 [[ -v SOURCE_WIKI_URL ]] || SOURCE_WIKI_URL='https://www.kicksecure.com/w'
 [[ -v DESTINATION_WIKI_URL ]] || DESTINATION_WIKI_URL=(
-   'https://www.whonix.org/w'
+  'https://www.whonix.org/w'
 )
 [[ -v wiki_backup_folder ]] || wiki_backup_folder=~/mediawiki-shell/mirror-multi-wiki
 
@@ -56,34 +56,35 @@ log info "wiki_multi_extra_wiki_pages_list: $wiki_multi_extra_wiki_pages_list"
 
 mkdir --parents "$wiki_backup_folder"
 
-if ! test -d "$wiki_backup_folder" ; then
-   log error "wiki_backup_folder '$wiki_backup_folder' does not exist! Run...?:"
-   stecho "mkdir --parents '$wiki_backup_folder'"
-   exit 1
+if ! test -d "$wiki_backup_folder"; then
+  log error "wiki_backup_folder '$wiki_backup_folder' does not exist! Run...?:"
+  stecho "mkdir --parents '$wiki_backup_folder'"
+  exit 1
 fi
 
-if ! test -w "$wiki_backup_folder" ; then
-   log error "wiki_backup_folder '$wiki_backup_folder' unwriteable! Run...?:"
-   stecho "chown --recursive '$USER:$USER' '$wiki_backup_folder'"
-   exit 1
+if ! test -w "$wiki_backup_folder"; then
+  log error "wiki_backup_folder '$wiki_backup_folder' unwriteable! Run...?:"
+  stecho "chown --recursive '$USER:$USER' '$wiki_backup_folder'"
+  exit 1
 fi
 
 WIKI_URL="$DESTINATION_WIKI_URL" \
-   mw-logout
+  mw-logout
 
 WIKI_URL="$DESTINATION_WIKI_URL" \
-   mw-login
+  mw-login
 
-all_pages="$($curl \
-   "${curl_opts[@]}" \
-   "${SOURCE_WIKI_API}?action=query&format=json&list=categorymembers&cmtitle=Category:$multiwiki_category&cmlimit=500"
+all_pages="$(
+  $curl \
+    "${curl_opts[@]}" \
+    "${SOURCE_WIKI_API}?action=query&format=json&list=categorymembers&cmtitle=Category:$multiwiki_category&cmlimit=500"
 )"
 
 ## TODO: cmcontinue
 #https://www.kicksecure.com/w/api.php?action=query&format=json&list=categorymembers&cmtitle=Category:MultiWiki&cmcontinue=page|434f444553454c454354|748
 
-for wiki_multi_extra_wiki_pages_item in $wiki_multi_extra_wiki_pages_list ; do
-   stecho "$wiki_multi_extra_wiki_pages_item" | tee -a "$allpages_file" >/dev/null
+for wiki_multi_extra_wiki_pages_item in $wiki_multi_extra_wiki_pages_list; do
+  stecho "$wiki_multi_extra_wiki_pages_item" | tee -a "$allpages_file" >/dev/null
 done
 
 stecho "$all_pages" | jq -r ".query.categorymembers[] | .title | @sh" | tee -a "$allpages_file" >/dev/null
@@ -93,84 +94,90 @@ result_test="$(stcat "$allpages_file")"
 counter_total="$(awk 'END {print NR}' "$allpages_file")"
 
 if [ "$result_test" = "" ]; then
-   log error "result_test is empty!"
-   exit 1
+  log error "result_test is empty!"
+  exit 1
 fi
 
 ## continue_from_page="Template:VM" mw-multi-wiki
 continue_next=no
 if [ "$continue_from_page" = "" ]; then
-   continue_next=yes
+  continue_next=yes
 fi
 
 counter_currently=0
-while IFS=$'\n' read -r item_from_all_pages ; do
-   counter_currently=$(( counter_currently + 1 ))
+while IFS=$'\n' read -r item_from_all_pages; do
+  counter_currently=$((counter_currently + 1))
 
-   backup_page_item="$item_from_all_pages"
-   ## remove last letter ("'")
-   backup_page_item="${backup_page_item::-1}"
-   ## remove first letter ("'")
-   backup_page_item="${backup_page_item:1}"
+  backup_page_item="$item_from_all_pages"
+  ## remove last letter ("'")
+  backup_page_item="${backup_page_item::-1}"
+  ## remove first letter ("'")
+  backup_page_item="${backup_page_item:1}"
 
-   search=" "
-   replace="_"
-   backup_page_item=$(stecho "$backup_page_item" | str_replace "$search" "$replace")
+  search=" "
+  replace="_"
+  backup_page_item=$(stecho "$backup_page_item" | str_replace "$search" "$replace")
 
-   stecho "PAGE | $counter_currently / $counter_total | $item_from_all_pages | $backup_page_item"
+  stecho "PAGE | $counter_currently / $counter_total | $item_from_all_pages | $backup_page_item"
 
-   if [ "${backup_page_item,,}" = "${continue_from_page,,}" ]; then
-      continue_next=yes
-   fi
-   if [ "$continue_next" = "no" ]; then
-      continue
-   fi
+  if [ "${backup_page_item,,}" = "${continue_from_page,,}" ]; then
+    continue_next=yes
+  fi
+  if [ "$continue_next" = "no" ]; then
+    continue
+  fi
 
-   copy_wiki_pages_exit_code=0
+  copy_wiki_pages_exit_code=0
 
-   SOURCE_WIKI_URL="$SOURCE_WIKI_URL" \
-   DESTINATION_WIKI_URL="$DESTINATION_WIKI_URL" \
-   TMPFOLDER="$TMPFOLDER" \
-   copy_wiki_pages_item="$backup_page_item" \
-   edit_message="mediawiki-shell-bot-mirror-multi-wiki-page-from-kicksecure-to-whonix" \
-      mw-copy-wiki-pages \
-         || { copy_wiki_pages_exit_code="$?" ; true; }
+  SOURCE_WIKI_URL="$SOURCE_WIKI_URL" \
+    DESTINATION_WIKI_URL="$DESTINATION_WIKI_URL" \
+    TMPFOLDER="$TMPFOLDER" \
+    copy_wiki_pages_item="$backup_page_item" \
+    edit_message="mediawiki-shell-bot-mirror-multi-wiki-page-from-kicksecure-to-whonix" \
+    mw-copy-wiki-pages ||
+    {
+      copy_wiki_pages_exit_code="$?"
+      true
+    }
 
-   if [ "$copy_wiki_pages_exit_code" = "10" ]; then
-      log warning "PAGE - Skipped backup_page_item '$backup_page_item' because of pending edits."
-   elif [ "$copy_wiki_pages_exit_code" = "0" ]; then
-      log info "PAGE - backup_page_item '$backup_page_item' mirroring success."
-   else
-      log error "PAGE - backup_page_item '$backup_page_item' mirroring error! copy_wiki_pages_exit_code: '$copy_wiki_pages_exit_code'"
-      exit 1
-   fi
+  if [ "$copy_wiki_pages_exit_code" = "10" ]; then
+    log warning "PAGE - Skipped backup_page_item '$backup_page_item' because of pending edits."
+  elif [ "$copy_wiki_pages_exit_code" = "0" ]; then
+    log info "PAGE - backup_page_item '$backup_page_item' mirroring success."
+  else
+    log error "PAGE - backup_page_item '$backup_page_item' mirroring error! copy_wiki_pages_exit_code: '$copy_wiki_pages_exit_code'"
+    exit 1
+  fi
 
-   if ! stecho "$backup_page_item" | grep --ignore-case -- "File:" >/dev/null 2>/dev/null; then
-      stecho "FILE | No, not a file, ok."
-      continue
-   fi
+  if ! stecho "$backup_page_item" | grep --ignore-case -- "File:" >/dev/null 2>/dev/null; then
+    stecho "FILE | No, not a file, ok."
+    continue
+  fi
 
-   stecho "FILE | $counter_currently / $counter_total | $item_from_all_pages | $backup_page_item"
+  stecho "FILE | $counter_currently / $counter_total | $item_from_all_pages | $backup_page_item"
 
-   copy_wiki_file_exit_code=0
+  copy_wiki_file_exit_code=0
 
-   SOURCE_WIKI_URL="$SOURCE_WIKI_URL" \
-   DESTINATION_WIKI_URL="$DESTINATION_WIKI_URL" \
-   TMPFOLDER="$TMPFOLDER" \
-   wiki_remote_file_name="$backup_page_item" \
-   edit_message="mediawiki-shell-bot-mirror-multi-wiki-file-from-kicksecure-to-whonix" \
-      mw-copy-wiki-file \
-         || { copy_wiki_file_exit_code="$?" ; true; }
+  SOURCE_WIKI_URL="$SOURCE_WIKI_URL" \
+    DESTINATION_WIKI_URL="$DESTINATION_WIKI_URL" \
+    TMPFOLDER="$TMPFOLDER" \
+    wiki_remote_file_name="$backup_page_item" \
+    edit_message="mediawiki-shell-bot-mirror-multi-wiki-file-from-kicksecure-to-whonix" \
+    mw-copy-wiki-file ||
+    {
+      copy_wiki_file_exit_code="$?"
+      true
+    }
 
-   if [ "$copy_wiki_file_exit_code" = "10" ]; then
-      log warning "FILE - Skipped backup_page_item '$backup_page_item' because of pending edits."
-   elif [ "$copy_wiki_file_exit_code" = "0" ]; then
-      log info "FILE - backup_page_item '$backup_page_item' mirroring success."
-   else
-      log error "FILE - backup_page_item '$backup_page_item' mirroring error! copy_wiki_pages_exit_code: '$copy_wiki_file_exit_code'"
-      exit 1
-   fi
+  if [ "$copy_wiki_file_exit_code" = "10" ]; then
+    log warning "FILE - Skipped backup_page_item '$backup_page_item' because of pending edits."
+  elif [ "$copy_wiki_file_exit_code" = "0" ]; then
+    log info "FILE - backup_page_item '$backup_page_item' mirroring success."
+  else
+    log error "FILE - backup_page_item '$backup_page_item' mirroring error! copy_wiki_pages_exit_code: '$copy_wiki_file_exit_code'"
+    exit 1
+  fi
 
-   continue
+  continue
 
-done < "$allpages_file"
+done <"$allpages_file"
diff --git a/usr/bin/mw-process-all-pages b/usr/bin/mw-process-all-pages
--- a/usr/bin/mw-process-all-pages
+++ b/usr/bin/mw-process-all-pages
@@ -45,66 +45,66 @@ chunk_max_size=10
 pid_list=""
 start_from_here="not-yet"
 
-while IFS=$'\n' read -r item_from_all_pages ; do
-   counter_currently=$(( counter_currently + 1 ))
-   backup_page_item=$(set_backup_page_item "$item_from_all_pages")
-   backup_filename_item=$(set_backup_filename_item "$backup_page_item")
+while IFS=$'\n' read -r item_from_all_pages; do
+  counter_currently=$((counter_currently + 1))
+  backup_page_item=$(set_backup_page_item "$item_from_all_pages")
+  backup_filename_item=$(set_backup_filename_item "$backup_page_item")
 
-   ## XXX
-   wiki_page_item="$backup_page_item"
-   wiki_article_to_fetch="$backup_page_item"
+  ## XXX
+  wiki_page_item="$backup_page_item"
+  wiki_article_to_fetch="$backup_page_item"
 
-   counter_chunk=$(( counter_chunk + 1 ))
+  counter_chunk=$((counter_chunk + 1))
 
-   ## TODO:
-   #continue_from_page="Network_Time_Synchronization"
+  ## TODO:
+  #continue_from_page="Network_Time_Synchronization"
 
-   if [ "$continue_from_page" = "" ]; then
+  if [ "$continue_from_page" = "" ]; then
+    start_from_here=true
+  else
+    if [ "${backup_page_item,,}" = "${continue_from_page,,}" ]; then
       start_from_here=true
-   else
-      if [ "${backup_page_item,,}" = "${continue_from_page,,}" ]; then
-         start_from_here=true
+    fi
+  fi
+
+  if [ ! "$start_from_here" = "true" ]; then
+    log info "skip: $counter_currently / $counter_total | counter_chunk: $counter_chunk | $backup_page_item | $backup_filename_item"
+    continue
+  fi
+  log notice "act: $counter_currently / $counter_total | counter_chunk: $counter_chunk | $backup_page_item | $backup_filename_item"
+
+  if [ "$backup_page_item" = "Changelog" ]; then
+    continue
+  fi
+
+  TMPFOLDER_SEPARATE="$TMPFOLDER/separate/$counter_currently"
+  mkdir --parents "$TMPFOLDER_SEPARATE"
+
+  run_background=1 log_run \
+    env \
+    counter_currently="$counter_currently" \
+    counter_chunk="$counter_chunk" \
+    TMPFOLDER="$TMPFOLDER_SEPARATE" \
+    WIKI_URL="$SOURCE_WIKI_URL" \
+    backup_page_item="$backup_page_item" \
+    backup_filename_item="$backup_filename_item" \
+    wiki_page_item="$wiki_page_item" \
+    wiki_article_to_fetch="$wiki_article_to_fetch" \
+    mw-retry-wrapper "$wiki_script"
+
+  pid_list+=" $background_pid"
+
+  if [ "$counter_chunk" -ge "$chunk_max_size" ] || [ "$counter_currently" -ge "$counter_total" ]; then
+    counter_chunk=0
+    log info "wait $pid_list"
+
+    for check_pid in $pid_list; do
+      if ! wait "$check_pid"; then
+        error "check_pid '$check_pid' failed!"
       fi
-   fi
+    done
 
-   if [ ! "$start_from_here" = "true" ]; then
-      log info "skip: $counter_currently / $counter_total | counter_chunk: $counter_chunk | $backup_page_item | $backup_filename_item"
-      continue
-   fi
-   log notice "act: $counter_currently / $counter_total | counter_chunk: $counter_chunk | $backup_page_item | $backup_filename_item"
+    pid_list=""
+  fi
 
-   if [ "$backup_page_item" = "Changelog" ]; then
-      continue
-   fi
-
-   TMPFOLDER_SEPARATE="$TMPFOLDER/separate/$counter_currently"
-   mkdir --parents "$TMPFOLDER_SEPARATE"
-
-   run_background=1 log_run \
-      env \
-         counter_currently="$counter_currently" \
-         counter_chunk="$counter_chunk" \
-         TMPFOLDER="$TMPFOLDER_SEPARATE" \
-         WIKI_URL="$SOURCE_WIKI_URL" \
-         backup_page_item="$backup_page_item" \
-         backup_filename_item="$backup_filename_item" \
-         wiki_page_item="$wiki_page_item" \
-         wiki_article_to_fetch="$wiki_article_to_fetch" \
-         mw-retry-wrapper "$wiki_script"
-
-   pid_list+=" $background_pid"
-
-   if [ "$counter_chunk" -ge "$chunk_max_size" ] || [ "$counter_currently" -ge "$counter_total" ] ; then
-      counter_chunk=0
-      log info "wait $pid_list"
-
-      for check_pid in $pid_list ; do
-         if ! wait "$check_pid" ; then
-            error "check_pid '$check_pid' failed!"
-         fi
-      done
-
-      pid_list=""
-   fi
-
-done < "$allpages_file"
+done <"$allpages_file"
diff --git a/usr/bin/mw-wiki-fetch-backup b/usr/bin/mw-wiki-fetch-backup
--- a/usr/bin/mw-wiki-fetch-backup
+++ b/usr/bin/mw-wiki-fetch-backup
@@ -9,91 +9,91 @@ source /usr/share/mediawiki-shell/common
 
 # shellcheck disable=SC2317
 exit_handler() {
-   [[ -v retry_counter ]] || retry_counter=0
-   if [ "$retry_counter" -gt 1 ]; then
-      ## >&2 is correct.
-      log notice "success after attempt $retry_counter"
-   fi
+  [[ -v retry_counter ]] || retry_counter=0
+  if [ "$retry_counter" -gt 1 ]; then
+    ## >&2 is correct.
+    log notice "success after attempt $retry_counter"
+  fi
 }
 
 trap exit_handler EXIT
 
 do_it() {
-   wiki_backup_file="${wiki_backup_folder}/${backup_filename_item}"
+  wiki_backup_file="${wiki_backup_folder}/${backup_filename_item}"
 
-   wiki_article_to_fetch="$backup_page_item" \
-   wiki_fetch_to_file="$wiki_backup_file" \
-   WIKI_URL="$SOURCE_WIKI_URL" \
-      mw-fetch
+  wiki_article_to_fetch="$backup_page_item" \
+    wiki_fetch_to_file="$wiki_backup_file" \
+    WIKI_URL="$SOURCE_WIKI_URL" \
+    mw-fetch
 
-   ## {{{
-   ## XXX
+  ## {{{
+  ## XXX
 
-   ## TODO: Should probably be done in mw-patch-modify-wiki-page
+  ## TODO: Should probably be done in mw-patch-modify-wiki-page
 
-   DESTINATION_WIKI_URL="$WIKI_URL"
+  DESTINATION_WIKI_URL="$WIKI_URL"
 
-   ## Remove trailing spaces.
-   sed -i 's/[[:space:]]*$//' "$wiki_backup_file"
+  ## Remove trailing spaces.
+  sed -i 's/[[:space:]]*$//' "$wiki_backup_file"
 
-#    if ! \
-#       WIKI_URL="$DESTINATION_WIKI_URL" \
-#       edit_message="remove-trailing-spaces" \
-#       mw-edit "$backup_page_item" "$wiki_backup_file" ; then
-#          log error "mw-edit '$backup_page_item' '$wiki_backup_file' failed!"
-#          return 1
-#    fi
+  #    if ! \
+  #       WIKI_URL="$DESTINATION_WIKI_URL" \
+  #       edit_message="remove-trailing-spaces" \
+  #       mw-edit "$backup_page_item" "$wiki_backup_file" ; then
+  #          log error "mw-edit '$backup_page_item' '$wiki_backup_file' failed!"
+  #          return 1
+  #    fi
 
-#   file_name="$wiki_backup_file"
-#
-#
-#   ## Ignore pages without header.
-#   if ! grep --ignore-case --fixed-strings --quiet -e "{{header" -- "$file_name"; then
-#     return 0
-#   fi
-#
-#   ## Ignore redirects.
-#   if grep --ignore-case --fixed-strings --quiet -e "#redirect [[" -- "$file_name"; then
-#     return 0
-#   fi
-#
-#   ## TODO: remove '!'
-#   ## Ignore pages without SEO.
-#   if ! grep --ignore-case --fixed-strings --quiet -e "{{#seo:" -- "$file_name"; then
-#     return 0
-#   fi
-#
-#   ## Ignore pages that already have a title.
-#   if grep --ignore-case --fixed-strings --quiet -e "{{title|" -- "$file_name"; then
-#     return 0
-#   fi
-#
-#   if grep --ignore-case --fixed-strings --quiet -e "title=" -- "$file_name"; then
-#     return 0
-#   fi
-#
-#   title="$backup_page_item"
-#   title="$(echo "$title" | str_replace ".mw" "")"
-#   title="$(echo "$title" | str_replace "_" " ")"
-#
-#    search="{{#seo:"
-#    replace="\
-# {{title|title=
-# $title
-# }}
-# {{#seo:"
-#
-#    str_replace "$search" "$replace" "$wiki_backup_file"
-#
-#    if ! \
-#       WIKI_URL="$DESTINATION_WIKI_URL" \
-#       edit_message="add-title" \
-#       mw-edit "$backup_page_item" "$wiki_backup_file" ; then
-#          log error "mw-edit '$backup_page_item' '$wiki_backup_file' failed!"
-#          return 1
-#    fi
+  #   file_name="$wiki_backup_file"
+  #
+  #
+  #   ## Ignore pages without header.
+  #   if ! grep --ignore-case --fixed-strings --quiet -e "{{header" -- "$file_name"; then
+  #     return 0
+  #   fi
+  #
+  #   ## Ignore redirects.
+  #   if grep --ignore-case --fixed-strings --quiet -e "#redirect [[" -- "$file_name"; then
+  #     return 0
+  #   fi
+  #
+  #   ## TODO: remove '!'
+  #   ## Ignore pages without SEO.
+  #   if ! grep --ignore-case --fixed-strings --quiet -e "{{#seo:" -- "$file_name"; then
+  #     return 0
+  #   fi
+  #
+  #   ## Ignore pages that already have a title.
+  #   if grep --ignore-case --fixed-strings --quiet -e "{{title|" -- "$file_name"; then
+  #     return 0
+  #   fi
+  #
+  #   if grep --ignore-case --fixed-strings --quiet -e "title=" -- "$file_name"; then
+  #     return 0
+  #   fi
+  #
+  #   title="$backup_page_item"
+  #   title="$(echo "$title" | str_replace ".mw" "")"
+  #   title="$(echo "$title" | str_replace "_" " ")"
+  #
+  #    search="{{#seo:"
+  #    replace="\
+  # {{title|title=
+  # $title
+  # }}
+  # {{#seo:"
+  #
+  #    str_replace "$search" "$replace" "$wiki_backup_file"
+  #
+  #    if ! \
+  #       WIKI_URL="$DESTINATION_WIKI_URL" \
+  #       edit_message="add-title" \
+  #       mw-edit "$backup_page_item" "$wiki_backup_file" ; then
+  #          log error "mw-edit '$backup_page_item' '$wiki_backup_file' failed!"
+  #          return 1
+  #    fi
 
-   ## }}}
+  ## }}}
 }
 
 check_vars_exist wiki_backup_folder backup_filename_item backup_page_item SOURCE_WIKI_URL
@@ -102,25 +102,25 @@ log info "wiki_backup_folder: $wiki_backup_folder"
 
 mkdir -p "$wiki_backup_folder"
 
-if ! test -d "$wiki_backup_folder" ; then
-   log error "wiki_backup_folder '$wiki_backup_folder' does not exist! Run...?:"
-   echo "mkdir --parents '$wiki_backup_folder'"
-   exit 1
+if ! test -d "$wiki_backup_folder"; then
+  log error "wiki_backup_folder '$wiki_backup_folder' does not exist! Run...?:"
+  echo "mkdir --parents '$wiki_backup_folder'"
+  exit 1
 fi
 
-if ! test -w "$wiki_backup_folder" ; then
-   log error "wiki_backup_folder '$wiki_backup_folder' unwriteable! Run...?:"
-   echo "chown --recursive '$USER:$USER' '$wiki_backup_folder'"
-   exit 1
+if ! test -w "$wiki_backup_folder"; then
+  log error "wiki_backup_folder '$wiki_backup_folder' unwriteable! Run...?:"
+  echo "chown --recursive '$USER:$USER' '$wiki_backup_folder'"
+  exit 1
 fi
 
-for retry_counter in $(seq 1 5) ; do
-   if do_it ; then
-      ## Success. Exit success.
-      exit 0
-   fi
-   ## Failed. Wait and try again.
-   sleep 5
+for retry_counter in $(seq 1 5); do
+  if do_it; then
+    ## Success. Exit success.
+    exit 0
+  fi
+  ## Failed. Wait and try again.
+  sleep 5
 done
 
 ## Failed even after retry attempts. Therefore exit non-zero.
diff --git a/usr/bin/mw-wiki-link-archiver b/usr/bin/mw-wiki-link-archiver
--- a/usr/bin/mw-wiki-link-archiver
+++ b/usr/bin/mw-wiki-link-archiver
@@ -12,160 +12,160 @@ set -o nounset
 log info "START"
 
 ensure_dir_exists() {
-   local dir_path
+  local dir_path
 
-   dir_path="${1:-}"
-   test -n "${dir_path}"
+  dir_path="${1-}"
+  test -n "${dir_path}"
 
-   if [ ! -d "${dir_path}" ]; then
-      if [ -e "${dir_path}" ]; then
-         log error "${dir_path} exists but is not a directory!"
-         exit 1
-      fi
-      mkdir -p "${dir_path}" || {
-         log error "Could not create a directory at ${dir_path}!"
-         exit 1
-      }
-   fi
+  if [ ! -d "${dir_path}" ]; then
+    if [ -e "${dir_path}" ]; then
+      log error "${dir_path} exists but is not a directory!"
+      exit 1
+    fi
+    mkdir -p "${dir_path}" || {
+      log error "Could not create a directory at ${dir_path}!"
+      exit 1
+    }
+  fi
 }
 
 ensure_file_exists() {
-   local file_path file_dir
+  local file_path file_dir
 
-   file_path="${1:-}"
-   test -n "${file_path}"
-   file_dir="$(dirname "${file_path}")"
+  file_path="${1-}"
+  test -n "${file_path}"
+  file_dir="$(dirname "${file_path}")"
 
-   ensure_dir_exists "${file_dir}"
-   touch "${file_path}" || {
-     log error "Could not touch ${file_path}!"
-     exit 1
-   }
+  ensure_dir_exists "${file_dir}"
+  touch "${file_path}" || {
+    log error "Could not touch ${file_path}!"
+    exit 1
+  }
 }
 
 ensure_wiki_git_up_to_date() {
-   local wiki_path wiki_git_repo archive_today_exit_code
+  local wiki_path wiki_git_repo archive_today_exit_code
 
-   wiki_path="${1:-}"
-   wiki_git_repo="${2:-}"
-   test -n "${wiki_path}"
-   test -n "${wiki_git_repo}"
+  wiki_path="${1-}"
+  wiki_git_repo="${2-}"
+  test -n "${wiki_path}"
+  test -n "${wiki_git_repo}"
 
-   pushd "${wiki_path}" >/dev/null
+  pushd "${wiki_path}" >/dev/null
 
-   if [ -d '.git' ]; then
-      git pull
-   else
-      if [ -z "$(find . -mindepth 1 -maxdepth 1)" ]; then
-         pushd .. >/dev/null
-         git clone --depth=1 "${wiki_git_repo}"
-         popd >/dev/null
-      else
-         log error "${wiki_path} has contents, but is not a Git repo!"
-         exit 1
-      fi
-   fi
+  if [ -d '.git' ]; then
+    git pull
+  else
+    if [ -z "$(find . -mindepth 1 -maxdepth 1)" ]; then
+      pushd .. >/dev/null
+      git clone --depth=1 "${wiki_git_repo}"
+      popd >/dev/null
+    else
+      log error "${wiki_path} has contents, but is not a Git repo!"
+      exit 1
+    fi
+  fi
 
-   popd >/dev/null
+  popd >/dev/null
 }
 
 wiki_link_archiver() {
-   local full_link_list archived_link_list captcha_cookie raw_link \
-      archived_link link_in_archived_list captcha_cookie_refresh_response
+  local full_link_list archived_link_list captcha_cookie raw_link \
+    archived_link link_in_archived_list captcha_cookie_refresh_response
 
-   ensure_file_exists "${full_link_list_file}"
-   ensure_file_exists "${archived_link_list_file}"
-   ensure_file_exists "${error_link_list_file}"
-   ensure_dir_exists "${kicksecure_wiki_path}"
-   ensure_dir_exists "${whonix_wiki_path}"
-   ensure_wiki_git_up_to_date "${kicksecure_wiki_path}" "${kicksecure_wiki_git_repo}"
-   ensure_wiki_git_up_to_date "${whonix_wiki_path}" "${whonix_wiki_git_repo}"
+  ensure_file_exists "${full_link_list_file}"
+  ensure_file_exists "${archived_link_list_file}"
+  ensure_file_exists "${error_link_list_file}"
+  ensure_dir_exists "${kicksecure_wiki_path}"
+  ensure_dir_exists "${whonix_wiki_path}"
+  ensure_wiki_git_up_to_date "${kicksecure_wiki_path}" "${kicksecure_wiki_git_repo}"
+  ensure_wiki_git_up_to_date "${whonix_wiki_path}" "${whonix_wiki_git_repo}"
 
-   echo 'Please paste in the CAPTCHA cookie obtained from your web browser.'
-   echo 'Press Enter to begin archiving.'
-   read -r captcha_cookie
+  echo 'Please paste in the CAPTCHA cookie obtained from your web browser.'
+  echo 'Press Enter to begin archiving.'
+  read -r captcha_cookie
 
-   # Generates full list of links, this takes a long time so any user input
-   # querying that can be moved before this line should be.
-   if [ "${skip_link_compilation}" = 'n' ]; then
-      mw-wiki-to-weblinks
-   fi
+  # Generates full list of links, this takes a long time so any user input
+  # querying that can be moved before this line should be.
+  if [ "${skip_link_compilation}" = 'n' ]; then
+    mw-wiki-to-weblinks
+  fi
 
-   readarray -t full_link_list < "${full_link_list_file}"
-   readarray -t archived_link_list < "${archived_link_list_file}"
+  readarray -t full_link_list <"${full_link_list_file}"
+  readarray -t archived_link_list <"${archived_link_list_file}"
 
-   for raw_link in "${full_link_list[@]}"; do
-      ## Skip links that we already know are archived.
-      link_in_archived_list='n'
-      for archived_link in "${archived_link_list[@]}"; do
-         if [ "${raw_link}" = "${archived_link}" ]; then
-            link_in_archived_list='y'
-            break
-         fi
-      done
-      if [ "${link_in_archived_list}" = 'y' ]; then
-         continue
+  for raw_link in "${full_link_list[@]}"; do
+    ## Skip links that we already know are archived.
+    link_in_archived_list='n'
+    for archived_link in "${archived_link_list[@]}"; do
+      if [ "${raw_link}" = "${archived_link}" ]; then
+        link_in_archived_list='y'
+        break
       fi
+    done
+    if [ "${link_in_archived_list}" = 'y' ]; then
+      continue
+    fi
 
-      ## Skip archive.org Wayback Machine links.
-      if [[ "${raw_link}" =~ ^https://web\.archive\.org/ ]]; then
-         continue
-      fi
-      ## Skip links that are already in archive.today.
-      if [[ "${raw_link}" =~ ^https://archive\.today/|^https://archive\.fo/|^https://archive\.is/|^https://archive\.li/|^https://archive\.md/|^https://archive\.ph/|^https://archive\.vn/ ]]; then
-         continue
-      fi
+    ## Skip archive.org Wayback Machine links.
+    if [[ ${raw_link} =~ ^https://web\.archive\.org/ ]]; then
+      continue
+    fi
+    ## Skip links that are already in archive.today.
+    if [[ ${raw_link} =~ ^https://archive\.today/|^https://archive\.fo/|^https://archive\.is/|^https://archive\.li/|^https://archive\.md/|^https://archive\.ph/|^https://archive\.vn/ ]]; then
+      continue
+    fi
 
-      ## Search for links in the archive, if something is already archived,
-      ## skip it
-      archive_today_exit_code='0'
-      archive.today --find --url "${raw_link}" --captcha-cookie "${captcha_cookie}" || archive_today_exit_code="$?"
-      sleep $(( ( RANDOM % 11 ) + 5 ))
-      if [ "${archive_today_exit_code}" = '0' ]; then
-         true
+    ## Search for links in the archive, if something is already archived,
+    ## skip it
+    archive_today_exit_code='0'
+    archive.today --find --url "${raw_link}" --captcha-cookie "${captcha_cookie}" || archive_today_exit_code="$?"
+    sleep $(((RANDOM % 11) + 5))
+    if [ "${archive_today_exit_code}" = '0' ]; then
+      true
+    else
+      ## Ensure the page exists and the site is up before trying to archive
+      ## NOTE! scurl **cannot** be used here, as it will fail on links that
+      ## have a less secure HTTPS configuration.
+      if [[ ${raw_link} =~ \.onion$ ]]; then
+        # Route onion links through Tor, assumes that tor is running
+        curl 2>/dev/null >/dev/null --proxy socks5h://127.0.0.1:9050 --location --fail "${raw_link}" || {
+          append-once "${error_link_list_file}" "${raw_link}"
+          continue
+        }
       else
-         ## Ensure the page exists and the site is up before trying to archive
-         ## NOTE! scurl **cannot** be used here, as it will fail on links that
-         ## have a less secure HTTPS configuration.
-         if [[ "${raw_link}" =~ \.onion$ ]]; then
-            # Route onion links through Tor, assumes that tor is running
-            2>/dev/null >/dev/null curl --proxy socks5h://127.0.0.1:9050 --location --fail "${raw_link}" || {
-               append-once "${error_link_list_file}" "${raw_link}"
-               continue
-            }
-         else
-            2>/dev/null >/dev/null curl --location --fail "${raw_link}" || {
-               append-once "${error_link_list_file}" "${raw_link}"
-               continue
-            }
-         fi
-
-         ## Try to archive the page, prompting the user for a new CAPTCHA
-         ## cookie if the archival attempt fails
-         while true; do
-            archive_today_exit_code='0'
-            archive.today --archive --url "${raw_link}" --captcha-cookie "${captcha_cookie}" || archive_today_exit_code="$?"
-            sleep $(( ( RANDOM % 11 ) + 5 ))
-            if [ "${archive_today_exit_code}" = '0' ]; then
-               break
-            else
-               log warning "New CAPTCHA cookie required!"
-               log warning "Please paste in the CAPTCHA cookie obtained from your web browser."
-               log warning "Alternatively, press N to skip this link without changing the cookie."
-               log warning "Press Enter to continue."
-               read -r captcha_cookie_refresh_response
-               if [ "${captcha_cookie_refresh_response,,}" = 'n' ]; then
-                  break
-               else
-                  captcha_cookie="${captcha_cookie_refresh_response}"
-               fi
-            fi
-         done
+        curl 2>/dev/null >/dev/null --location --fail "${raw_link}" || {
+          append-once "${error_link_list_file}" "${raw_link}"
+          continue
+        }
       fi
 
-      archived_link_list+=( "${raw_link}" )
-      append-once "${archived_link_list_file}" "${raw_link}"
-   done
+      ## Try to archive the page, prompting the user for a new CAPTCHA
+      ## cookie if the archival attempt fails
+      while true; do
+        archive_today_exit_code='0'
+        archive.today --archive --url "${raw_link}" --captcha-cookie "${captcha_cookie}" || archive_today_exit_code="$?"
+        sleep $(((RANDOM % 11) + 5))
+        if [ "${archive_today_exit_code}" = '0' ]; then
+          break
+        else
+          log warning "New CAPTCHA cookie required!"
+          log warning "Please paste in the CAPTCHA cookie obtained from your web browser."
+          log warning "Alternatively, press N to skip this link without changing the cookie."
+          log warning "Press Enter to continue."
+          read -r captcha_cookie_refresh_response
+          if [ "${captcha_cookie_refresh_response,,}" = 'n' ]; then
+            break
+          else
+            captcha_cookie="${captcha_cookie_refresh_response}"
+          fi
+        fi
+      done
+    fi
+
+    archived_link_list+=("${raw_link}")
+    append-once "${archived_link_list_file}" "${raw_link}"
+  done
 }
 
 ## Set global tunables
diff --git a/usr/share/mediawiki-shell/common b/usr/share/mediawiki-shell/common
--- a/usr/share/mediawiki-shell/common
+++ b/usr/share/mediawiki-shell/common
@@ -22,18 +22,18 @@ check_vars_exist() {
 }
 
 missing_variable() {
-   log error "MISSING VARIABLE: $*"
-   exit 1
+  log error "MISSING VARIABLE: $*"
+  exit 1
 }
 
 error_output() {
-   [[ -v WIKI_INDEX ]] || WIKI_INDEX=""
-   [[ -v TITLE ]] || TITLE=""
-   [[ -v BASH_COMMAND ]] || BASH_COMMAND=""
-   [[ -v counter_chunk ]] || counter_chunk="unset"
-   [[ -v counter_currently ]] || counter_currently="unset"
-   [[ -v TMPFOLDER ]] || TMPFOLDER="unset"
-   echo "error_msg: '${1:-unset}'
+  [[ -v WIKI_INDEX ]] || WIKI_INDEX=""
+  [[ -v TITLE ]] || TITLE=""
+  [[ -v BASH_COMMAND ]] || BASH_COMMAND=""
+  [[ -v counter_chunk ]] || counter_chunk="unset"
+  [[ -v counter_currently ]] || counter_currently="unset"
+  [[ -v TMPFOLDER ]] || TMPFOLDER="unset"
+  echo "error_msg: '${1:-unset}'
 WIKI_INDEX: '$WIKI_INDEX'
 TITLE: '$TITLE'
 TMPFOLDER: '$TMPFOLDER'
@@ -43,148 +43,151 @@ counter_currently: '$counter_currently'
 }
 
 error_handler() {
-   last_exit_code="$?"
-   log error "
+  last_exit_code="$?"
+  log error "
 BASH_COMMAND: '$BASH_COMMAND'
 failed with exit code '$last_exit_code'." >&2
-   error_output "called-by-error_handler"
-   exit 1
+  error_output "called-by-error_handler"
+  exit 1
 }
 
 trap error_handler ERR
 
 exit_handler() {
-   trap - INT HUP ABRT QUIT EXIT
-   local exit_code=$1
-   if [ "$exit_code" = "0" ]; then
-      log notice "END: with OK exit code: '$exit_code'"
-   else
-      log error "END: with ERROR exit code: '$exit_code'"
-   fi
-   exit "$exit_code"
+  trap - INT HUP ABRT QUIT EXIT
+  local exit_code=$1
+  if [ "$exit_code" = "0" ]; then
+    log notice "END: with OK exit code: '$exit_code'"
+  else
+    log error "END: with ERROR exit code: '$exit_code'"
+  fi
+  exit "$exit_code"
 }
 
 set_curl_binary_default() {
-   if command -v scurl &>/dev/null ; then
-      curl=scurl
-   else
-      curl=curl
-   fi
+  if command -v scurl &>/dev/null; then
+    curl=scurl
+  else
+    curl=curl
+  fi
 }
 
 set_backup_page_item() {
-   local backup_page_item search replace
+  local backup_page_item search replace
 
-   backup_page_item="$1"
+  backup_page_item="$1"
 
-   if [ "$backup_page_item" = "" ]; then
-      error "set_backup_filename_item is empty!"
-   fi
+  if [ "$backup_page_item" = "" ]; then
+    error "set_backup_filename_item is empty!"
+  fi
 
-   ## remove last letter ("'")
-   backup_page_item="${backup_page_item::-1}"
-   ## remove first letter ("'")
-   backup_page_item="${backup_page_item:1}"
+  ## remove last letter ("'")
+  backup_page_item="${backup_page_item::-1}"
+  ## remove first letter ("'")
+  backup_page_item="${backup_page_item:1}"
 
-   search="'\''"
-   replace="'"
-   backup_page_item=$(echo "$backup_page_item" | str_replace "$search" "$replace")
+  search="'\''"
+  replace="'"
+  backup_page_item=$(echo "$backup_page_item" | str_replace "$search" "$replace")
 
-   search="&"
-   replace="%26"
-   backup_page_item=$(echo "$backup_page_item" | str_replace "$search" "$replace")
+  search="&"
+  replace="%26"
+  backup_page_item=$(echo "$backup_page_item" | str_replace "$search" "$replace")
 
-   ## Same format as git-mediawiki: replace ' ' with '_'.
-   ## Replace spaces with underscore.
-   search=" "
-   replace="_"
-   backup_page_item=$(echo "$backup_page_item" | str_replace "$search" "$replace")
+  ## Same format as git-mediawiki: replace ' ' with '_'.
+  ## Replace spaces with underscore.
+  search=" "
+  replace="_"
+  backup_page_item=$(echo "$backup_page_item" | str_replace "$search" "$replace")
 
-   echo "$backup_page_item"
+  echo "$backup_page_item"
 }
 
 set_backup_filename_item() {
-   local backup_filename_item search replace
+  local backup_filename_item search replace
 
-   backup_filename_item="$1"
+  backup_filename_item="$1"
 
-   if [ "$backup_filename_item" = "" ]; then
-      error "backup_filename_item is empty!"
-   fi
+  if [ "$backup_filename_item" = "" ]; then
+    error "backup_filename_item is empty!"
+  fi
 
-   ## Same format as git-mediawiki: replace '/' with '%2F'.
-   ## Also the file system does not accept files containing '/'.
-   search="/"
-   replace="%2F"
-   backup_filename_item=$(echo "$backup_filename_item" | str_replace "$search" "$replace")
+  ## Same format as git-mediawiki: replace '/' with '%2F'.
+  ## Also the file system does not accept files containing '/'.
+  search="/"
+  replace="%2F"
+  backup_filename_item=$(echo "$backup_filename_item" | str_replace "$search" "$replace")
 
-   ## Same format as git-mediawiki: add '.mw' file extension.
-   backup_filename_item="${backup_filename_item}.mw"
+  ## Same format as git-mediawiki: add '.mw' file extension.
+  backup_filename_item="${backup_filename_item}.mw"
 
-   echo "$backup_filename_item"
+  echo "$backup_filename_item"
 }
 
 curl_get_output_parameter() {
-   local loop_counter
-   loop_counter=0
+  local loop_counter
+  loop_counter=0
 
-   while true; do
-      loop_counter=$(( loop_counter + 1 ))
-      if [ "$loop_counter" -ge 50 ]; then
-         error "loop_max reached!"
-         exit 1
-      fi
-      case $1 in
-         --output)
-            output_file="$2"
-            shift 2
-            break
-            ;;
-         *)
-            shift
-            ;;
-      esac
-   done
+  while true; do
+    loop_counter=$((loop_counter + 1))
+    if [ "$loop_counter" -ge 50 ]; then
+      error "loop_max reached!"
+      exit 1
+    fi
+    case $1 in
+      --output)
+        output_file="$2"
+        shift 2
+        break
+        ;;
+      *)
+        shift
+        ;;
+    esac
+  done
 }
 
 curl_run() {
-   ## Do not destroy "$@" in this function. Therefore passing it to a different
-   ## helper function so it stays local there and unchanged here.
-   curl_get_output_parameter "$@"
+  ## Do not destroy "$@" in this function. Therefore passing it to a different
+  ## helper function so it stays local there and unchanged here.
+  curl_get_output_parameter "$@"
 
-   if [ -z "$output_file" ]; then
-      error "output_file is empty!"
-      exit 1
-   fi
+  if [ -z "$output_file" ]; then
+    error "output_file is empty!"
+    exit 1
+  fi
 
-   rm -f "$output_file"
-   touch "$output_file"
+  rm -f "$output_file"
+  touch "$output_file"
 
-   local args url encoded_url
-   # shellcheck disable=SC2124,SC1126
-   url="${@: -1}"
+  local args url encoded_url
+  # shellcheck disable=SC2124,SC1126
+  url="${@: -1}"
 
-   [[ -v curl_run_no_encode ]] || curl_run_no_encode=""
+  [[ -v curl_run_no_encode ]] || curl_run_no_encode=""
 
-   if [ "$curl_run_no_encode" = "true" ]; then
-      encoded_url="$url"
-   else
-      encoded_url="$(mw-urlencode "$url")"
-   fi
+  if [ "$curl_run_no_encode" = "true" ]; then
+    encoded_url="$url"
+  else
+    encoded_url="$(mw-urlencode "$url")"
+  fi
 
-   # Rebuild the arguments excluding the last parameter, then append the encoded URL
-   args=("${@:1:$#-1}" "$encoded_url")
+  # Rebuild the arguments excluding the last parameter, then append the encoded URL
+  args=("${@:1:$#-1}" "$encoded_url")
 
-   curl_exit_code=0
+  curl_exit_code=0
 
-   # Run curl with the modified arguments
-   $curl "${args[@]}" || { curl_exit_code=$?; true; }
+  # Run curl with the modified arguments
+  $curl "${args[@]}" || {
+    curl_exit_code=$?
+    true
+  }
 
-   if [ ! "$curl_exit_code" = "0" ]; then
-      log error "curl result failed with exit code '$curl_exit_code'. output_file: $output_file"
-      cat "$output_file" >&2
-      exit 1
-   fi
+  if [ ! "$curl_exit_code" = "0" ]; then
+    log error "curl result failed with exit code '$curl_exit_code'. output_file: $output_file"
+    cat "$output_file" >&2
+    exit 1
+  fi
 }
 
 trap 'exit_handler $?' INT HUP ABRT QUIT EXIT
@@ -194,14 +197,14 @@ trap 'exit_handler $?' INT HUP ABRT QUIT EXIT
 [[ -v cookie_jar ]] || cookie_jar="$TMPFOLDER/wiki-cookiejar"
 [[ -v curl ]] || set_curl_binary_default
 [[ -v curl_opts ]] || curl_opts=(
-   "--fail"
-   "--no-progress-meter"
-   "--show-error"
-   "--retry-connrefused"
-   "--retry" "10"
-   "--retry-delay" "5"
-   "--cookie" "nocache=true"
-   "--user-agent" "mediawiki-shell"
+  "--fail"
+  "--no-progress-meter"
+  "--show-error"
+  "--retry-connrefused"
+  "--retry" "10"
+  "--retry-delay" "5"
+  "--cookie" "nocache=true"
+  "--user-agent" "mediawiki-shell"
 )
 
 mkdir --parents "$TMPFOLDER"
