Stricter shell options

diff --git a/usr/bin/mw-login b/usr/bin/mw-login
--- a/usr/bin/mw-login
+++ b/usr/bin/mw-login
@@ -1,6 +1,5 @@
-#!/bin/bash
-
-set -e
+#!/usr/bin/env bash
+set -euEo pipefail
 
 # shellcheck source=../share/mediawiki-shell/common
 source /usr/share/mediawiki-shell/common
@@ -14,8 +13,7 @@ fi
 
 log info "Login into '$WIKI_API' as '$WIKI_API_USER_NAME'... Requesting Login token..."
 
-rm -f "${TMPFOLDER}/login-token.json"
-rm -f "${TMPFOLDER}/login-result.json"
+rm -f -- "${TMPFOLDER}"/login-{token,result}.json
 
 curl_run \
   "${curl_opts[@]}" \
@@ -28,11 +26,7 @@ curl_run \
   "${WIKI_API}?action=query&meta=tokens&type=login&format=json"
 
 log info "Login Token received."
-
-login_token="$(jq --raw-output '.query.tokens.logintoken' <"${TMPFOLDER}/login-token.json")"
-
-## Sensitive?
-#log info "login_token: $login_token"
+login_token="$(jq --raw-output '.query.tokens.logintoken' -- "${TMPFOLDER}/login-token.json")"
 
 curl_run \
   "${curl_opts[@]}" \
@@ -53,13 +47,12 @@ curl_run \
 ## "result": "Aborted",
 ## "reason": "Cannot log in when using MediaWiki\\Session\\BotPasswordSessionProvider sessions."
 
-RESULT="$(jq -r '.login.result' <"${TMPFOLDER}/login-result.json")"
+RESULT="$(jq --raw-output '.login.result' -- "${TMPFOLDER}/login-result.json")"
 
 if [ "$RESULT" = "Success" ]; then
   log info "Successfully logged in as '$WIKI_API_USER_NAME'."
   exit 0
 fi
 
-jq "${TMPFOLDER}/login-result.json" >&2
-log error "Login failed!"
-exit 1
+jq . -- "${TMPFOLDER}/login-result.json" >&2
+die 1 "Login failed!"
diff --git a/usr/bin/mw-logout b/usr/bin/mw-logout
--- a/usr/bin/mw-logout
+++ b/usr/bin/mw-logout
@@ -1,6 +1,5 @@
-#!/bin/bash
-
-set -e
+#!/usr/bin/env bash
+set -euEo pipefail
 
 # shellcheck source=../share/mediawiki-shell/common
 source /usr/share/mediawiki-shell/common
@@ -8,7 +7,6 @@ source /usr/share/mediawiki-shell/common
 source /usr/share/mediawiki-shell/wiki-config
 
 log info "Logging out of $WIKI_API... Requesting CSRF token..."
-
 rm -f -- "${TMPFOLDER}/logout-token.json"
 
 curl_run \
@@ -20,10 +18,8 @@ curl_run \
   --output "${TMPFOLDER}/logout-token.json" \
   --request "POST" \
   "${WIKI_API}?action=query&meta=tokens&type=csrf&format=json"
-
 log info "Token received."
-
-csrf_token="$(cat -- "${TMPFOLDER}/logout-token.json" | jq --raw-output '.query.tokens.csrftoken')"
+csrf_token="$(jq --raw-output '.query.tokens.csrftoken' -- "${TMPFOLDER}/logout-token.json")"
 
 curl_run \
   "${curl_opts[@]}" \
@@ -35,16 +31,12 @@ curl_run \
   --request "POST" \
   "${WIKI_API}?action=logout&format=json"
 
-if [ "$(cat -- "${TMPFOLDER}/logout.json")" = "{}" ]; then
+if [ "$(cat -- "${TMPFOLDER}/logout.json")" = "{}" ] ||
+  [ "$(jq --raw-output '.warnings.logout."*"' -- "${TMPFOLDER}/logout.json")" = "You must be logged in." ]
+then
   log info "OK, logged out."
   exit 0
 fi
 
-if [ "$(cat -- "${TMPFOLDER}/logout.json" | jq -r '.warnings.logout."*"')" = "You must be logged in." ]; then
-  log info "OK, logged out."
-  exit 0
-fi
-
-cat -- "${TMPFOLDER}/logout.json" | jq >&2
-log error "Logout failed!"
-exit 1
+jq . -- "${TMPFOLDER}/logout.json" >&2
+die 1 "Logout failed!"
