Add logging helper

diff --git a/usr/bin/mw-login b/usr/bin/mw-login
--- a/usr/bin/mw-login
+++ b/usr/bin/mw-login
@@ -7,12 +7,12 @@ source /usr/share/mediawiki-shell/common
 # shellcheck source=../share/mediawiki-shell/wiki-config
 source /usr/share/mediawiki-shell/wiki-config
 
-if [ -z "$WIKI_API_USER_PASS" ]; then
-   echo "$0: ERROR: Password not supplied!" >&2
+if [ -z "${WIKI_API_USER_PASS-}" ]; then
+   log error "Password not supplied!"
    exit 1
 fi
 
-true "$0: INFO: Logging into '$WIKI_API' as '$WIKI_API_USER_NAME'... Requesting Login token..."
+log info "Login into '$WIKI_API' as '$WIKI_API_USER_NAME'... Requesting Login token..."
 
 rm -f "${TMPFOLDER}/login-token.json"
 rm -f "${TMPFOLDER}/login-result.json"
@@ -27,12 +27,12 @@ curl_run \
    --request "POST" \
    "${WIKI_API}?action=query&meta=tokens&type=login&format=json"
 
-true "$0: INFO: Login Token received."
+log info "Login Token received."
 
-login_token=$(cat "${TMPFOLDER}/login-token.json" | jq --raw-output '.query.tokens.logintoken')
+login_token="$(jq --raw-output '.query.tokens.logintoken' < "${TMPFOLDER}/login-token.json")"
 
 ## Sensitive?
-#echo "$0: INFO: login_token: $login_token"
+#log info "login_token: $login_token"
 
 curl_run \
    "${curl_opts[@]}" \
@@ -53,13 +53,13 @@ curl_run \
 ## "result": "Aborted",
 ## "reason": "Cannot log in when using MediaWiki\\Session\\BotPasswordSessionProvider sessions."
 
-RESULT=$(cat "${TMPFOLDER}/login-result.json" | jq -r '.login.result')
+RESULT="$(jq -r '.login.result' < "${TMPFOLDER}/login-result.json")"
 
 if [ "$RESULT" = "Success" ]; then
-   true "$0: INFO: Successfully logged in as '$WIKI_API_USER_NAME'."
+   log info "Successfully logged in as '$WIKI_API_USER_NAME'."
    exit 0
 fi
 
-cat "${TMPFOLDER}/login-result.json" | jq >&2
-echo "$0: ERROR: Login failed!" >&2
+jq "${TMPFOLDER}/login-result.json" >&2
+log error "Login failed!"
 exit 1
diff --git a/usr/share/mediawiki-shell/common b/usr/share/mediawiki-shell/common
--- a/usr/share/mediawiki-shell/common
+++ b/usr/share/mediawiki-shell/common
@@ -4,22 +4,25 @@ set -euo pipefail -o errtrace
 
 log_level=info
 source /usr/libexec/helper-scripts/log_run_die.sh
+source /usr/libexec/helper-scripts/has.sh
 
-if ! command -v retry >/dev/null ; then
-   echo "ERROR: 'retry' command unavailable! Probably 'retry' package is not installed." >&2
-fi
+for cmd in retry curl jq; do
+  if ! has "$cmd"; then
+    die 1 "'${cmd}' command is unavailable!" >&2
+  fi
+done
 
 check_vars_exist() {
   for var_name in "$@"; do
     if [ -z "${!var_name+x}" ]; then
-      echo "ERROR: Variable '$var_name' is not set or is empty." >&2
+      die 1 "Variable '$var_name' is not set or is empty."
       exit 1
     fi
   done
 }
 
 missing_variable() {
-   echo "$0: ERROR: MISSING VARIABLE: $*"
+   log error "MISSING VARIABLE: $*"
    exit 1
 }
 
@@ -41,13 +44,10 @@ counter_currently: '$counter_currently'
 
 error_handler() {
    last_exit_code="$?"
-   echo "###
-$0: ERROR:
+   log error "
 BASH_COMMAND: '$BASH_COMMAND'
 failed with exit code '$last_exit_code'." >&2
-
    error_output "called-by-error_handler"
-
    exit 1
 }
 
@@ -57,9 +57,9 @@ exit_handler() {
    trap - INT HUP ABRT QUIT EXIT
    local exit_code=$1
    if [ "$exit_code" = "0" ]; then
-      echo "## $0: END: with OK exit code: '$exit_code'"
+      log notice "END: with OK exit code: '$exit_code'"
    else
-      echo "## $0: END: with ERROR exit code: '$exit_code'"
+      log error "END: with ERROR exit code: '$exit_code'"
    fi
    exit "$exit_code"
 }
@@ -181,7 +181,7 @@ curl_run() {
    $curl "${args[@]}" || { curl_exit_code=$?; true; }
 
    if [ ! "$curl_exit_code" = "0" ]; then
-      echo "$0: ERROR: curl result failed with exit code '$curl_exit_code'. output_file: $output_file" >&2
+      log error "curl result failed with exit code '$curl_exit_code'. output_file: $output_file"
       cat "$output_file" >&2
       exit 1
    fi
