.

diff --git a/usr/share/mediawiki-shell/common b/usr/share/mediawiki-shell/common
--- a/usr/share/mediawiki-shell/common
+++ b/usr/share/mediawiki-shell/common
@@ -5,7 +5,18 @@ set -e
 set -o pipefail
 set -o nounset
 
-command -v retry >/dev/null
+if ! command -v retry >/dev/null ; then
+   echo "ERROR: 'retry' command unavailable! Probably 'retry' package is not installed." >&2
+fi
+
+check_vars_exist() {
+  for var_name in "$@"; do
+    if [ -z "${!var_name+x}" ]; then
+      echo "ERROR: Variable '$var_name' is not set or is empty." >&2
+      exit 1
+    fi
+  done
+}
 
 missing_variable() {
    echo "$0: ERROR: MISSING VARIABLE: $@"
