.

diff --git a/usr/share/mediawiki-shell/common b/usr/share/mediawiki-shell/common
--- a/usr/share/mediawiki-shell/common
+++ b/usr/share/mediawiki-shell/common
@@ -104,6 +104,59 @@ set_backup_filename_item() {
    echo "$backup_filename_item"
 }
 
+curl_get_output_parameter() {
+   local loop_counter
+   loop_counter=0
+
+   while true ; do
+      loop_counter=$(( loop_counter + 1))
+      if [ "$loop_counter" -ge 50 ]; then
+         error "loop_max reached!"
+         exit 1
+      fi
+      case $1 in
+         --output)
+            output_file="$2"
+            shift 2
+            break
+            ;;
+         *)
+            shift
+            ;;
+      esac
+   done
+}
+
+curl_run() {
+   ## Do not destroy "$@" in this function. Therefore passing it to a different
+   ## helper function so it stays local there and unchanged here.
+   curl_get_output_parameter "$@"
+
+   #echo "$0: INFO: output_file: '$output_file'"
+
+   if [ "$output_file" = "" ]; then
+      error "output_file is empty!"
+      exit 1
+   fi
+
+   rm -f "$output_file"
+   touch "$output_file"
+
+   curl_exit_code=0
+
+   $curl \
+      "$@" \
+      || { curl_exit_code=$? ; true; };
+
+   #echo "$0: INFO: curl result  exit code '$curl_exit_code'. output_file: $output_file"
+
+   if [ ! "$curl_exit_code" = "0" ]; then
+      echo "$0: ERROR: curl result failed with exit code '$curl_exit_code'. output_file: $output_file" >&2
+      cat "$output_file" >&2
+      exit 1
+   fi
+}
+
 trap exit_handler EXIT
 
 [[ -v TMPFOLDER ]] || TMPFOLDER=~/mediawiki-shell/temp
@@ -112,7 +165,7 @@ trap exit_handler EXIT
 [[ -v curl ]] || set_curl_binary_default
 [[ -v curl_opts ]] || curl_opts="\
    --fail \
-   --silent \
+   --no-progress-meter \
    --show-error \
    --retry-connrefused \
    --retry 3 \
